"use client";
import { useEffect,useState } from "react";
import { AppShell } from "@/components/layout/app-shell";
import { Medal,Trophy } from "lucide-react";
import { useGame } from "@/components/state/game-provider";
import { rankForRp,rankLabel } from "@/lib/season/engine";
import { createClient } from "@/lib/supabase/client";
const tabs=["OVERALL","DISTANCE","QUESTS","CONSISTENCY","SOCIAL","CHECKPOINTS"] as const;
type Row={id:string;name:string;avatar:string;rank:number;score:number};type LiveRow={user_id:string;display_name:string;avatar_url:string|null;rank:number;score:number};
export default function Leaderboard(){const [tab,setTab]=useState<typeof tabs[number]>("OVERALL"),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),{state}=useGame();useEffect(()=>{const client=createClient();if(!client){setError("Live database is unavailable");setLoading(false);return}setLoading(true);void client.rpc("get_live_leaderboard",{p_category:tab.toLowerCase(),p_limit:100}).then(({data,error:queryError})=>{if(queryError)setError(queryError.message);else{setRows(((data||[]) as LiveRow[]).map(row=>({id:row.user_id,name:row.display_name,avatar:row.avatar_url||"🏃",rank:Number(row.rank),score:Number(row.score)})));setError("")}setLoading(false)})},[tab]);return <AppShell title="LEADERBOARD"><main className="mx-auto max-w-3xl px-4 py-8 md:px-8"><div className="text-center"><span className="mx-auto grid size-16 place-items-center rounded-2xl bg-[#ffd43b] text-[#111]"><Trophy size={30}/></span><p className="eyebrow mt-5">{state.seasonState.season.name}</p><h1 className="game-title mt-2 text-5xl">MONTHLY {tab}</h1><p className="muted mt-3 text-xs">Only verified database activity appears in this ranking.</p></div><div className="scrollbar-none mt-7 flex gap-2 overflow-auto pb-2">{tabs.map(item=><button onClick={()=>setTab(item)} key={item} className={`shrink-0 rounded-xl border px-4 py-2.5 text-[.55rem] font-black ${tab===item?"border-[#b7ff22] bg-[#b7ff22] text-[#111]":"border-[#34374b] bg-[#1a1c2e]"}`}>{item}</button>)}</div>{loading?<div className="skeleton mt-4 h-64 rounded-3xl"/>:error?<Empty title="RANKING UNAVAILABLE" detail={error}/>:rows.length===0?<Empty title="NO VERIFIED RANKINGS YET" detail="The leaderboard will populate after real verified runs are processed."/>:<div className="panel mt-4 overflow-hidden">{rows.map(row=>{const tier=rankForRp(tab==="OVERALL"?row.score:0);return <div key={row.id} className="flex items-center gap-3 border-b border-[#2d3045] p-4 last:border-0"><b className={`w-8 text-center text-lg ${row.rank<4?"text-[#ffd43b]":"text-[#72768a]"}`}>{row.rank}</b><span className="grid size-11 place-items-center rounded-full bg-[#9577d7] text-3xl">{row.avatar}</span><span className="min-w-0 flex-1"><b className="block truncate text-xs">{row.name.toUpperCase()}</b>{tab==="OVERALL"&&<small className="text-[.48rem] font-black" style={{color:tier.color}}>{tier.icon} {rankLabel(tier)}</small>}</span><span className="text-right"><b className="block text-sm">{row.score.toLocaleString()} {tab==="OVERALL"?"RP":tab==="DISTANCE"?"KM":""}</b><small className="text-[.46rem] text-[#7f8396]">VERIFIED</small></span>{row.rank<4&&<Medal size={17} className="text-[#ffd43b]"/>}</div>})}</div>}<p className="mt-4 text-center text-[.53rem] text-[#777b8e]">Speed alone never determines Overall Rank.</p></main></AppShell>}
function Empty({title,detail}:{title:string;detail:string}){return <div className="panel mt-4 p-8 text-center"><b>{title}</b><p className="muted mx-auto mt-2 max-w-md text-xs leading-5">{detail}</p></div>}
