"use client";
import { useState } from "react";
import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { GameMapLoader } from "@/components/map/game-map-loader";
import { PublicRunList } from "@/components/game/public-run-list";
import { worlds,quests } from "@/data/game-content";
import { Check,ChevronRight,Route } from "lucide-react";
export default function Explore(){const [worldId,setWorldId]=useState("world-2"),activeWorld=worlds.find(w=>w.id===worldId)??worlds[1],visible=quests.filter(q=>q.worldId===worldId).slice(0,5);return <AppShell title="EXPLORE"><main className="mx-auto max-w-7xl px-4 py-7 md:px-8"><div><p className="eyebrow">VIENTIANE • {activeWorld.name}</p><h1 className="game-title mt-2 text-4xl md:text-5xl">PICK YOUR NEXT <span className="text-[#b7ff22]">ADVENTURE.</span></h1></div><div aria-label="Choose quest world" className="scrollbar-none mt-7 flex gap-2 overflow-x-auto pb-2">{worlds.map(w=>{const active=worldId===w.id;return <button aria-pressed={active} onClick={()=>setWorldId(w.id)} key={w.id} className={`relative flex min-w-[178px] items-center gap-3 overflow-hidden rounded-2xl border p-2.5 text-left transition active:scale-[.98] ${active?"border-[#b7ff22] bg-[#272438] shadow-[0_0_0_2px_rgba(183,255,34,.12)]":"border-[#303348] bg-[#171927]"}`}><span className="grid size-11 shrink-0 place-items-center rounded-xl text-xs font-black text-[#111]" style={{background:w.color}}>0{w.number}</span><span className="min-w-0"><b className={`block truncate text-[.62rem] ${active?"text-white":"text-[#c3c5d0]"}`}>{w.name}</b><small className="mt-1 block truncate text-[.5rem] text-[#8f93a5]">{active?`${quests.filter(q=>q.worldId===w.id).length} QUESTS ON MAP`:w.subtitle}</small></span>{active&&<span className="absolute right-2 top-2 grid size-5 place-items-center rounded-full bg-[#b7ff22] text-[#111]"><Check size={11} strokeWidth={4}/></span>}</button>})}</div><div className="mt-4 h-[58vh] min-h-[520px]"><GameMapLoader worldId={worldId}/></div><PublicRunList/><section className="mt-9"><div className="flex items-center justify-between"><h2 className="text-xl font-black">{activeWorld.name} QUESTS</h2><span className="text-[.55rem] font-black text-[#85899c]">{visible.length} QUESTS</span></div><div className="mt-4 grid gap-3 md:grid-cols-3">{visible.map(q=><Link key={q.id} href={`/quest/${q.id}`} className="panel lift flex items-center gap-3 p-3"><span className="grid size-14 place-items-center rounded-xl text-2xl text-[#111]" style={{background:activeWorld.color}}>{q.type==="boss"?"🏆":q.type==="team"?"👥":"⚡"}</span><span className="min-w-0 flex-1"><small className="text-[.48rem] font-black text-[#85899b]">{q.type.toUpperCase()} QUEST</small><b className="mt-1 block truncate text-[.67rem]">{q.name}</b><span className="mt-1 flex items-center gap-1.5 text-[.52rem] text-[#85899b]"><Route size={11}/>{q.distanceKm} KM • VERIFIED GPS REQUIRED</span></span><ChevronRight size={16}/></Link>)}</div></section></main></AppShell>}
