"use client";
import { useMemo } from "react";
import { useRouter } from "next/navigation";
import { Share2,ShieldCheck,Trophy } from "lucide-react";
import { achievements as allAchievements } from "@/data/game-content";
import { rankTiers } from "@/data/season";
import { useGame } from "@/components/state/game-provider";
import { rankForRp,rankLabel } from "@/lib/season/engine";
import { useLiveRunners } from "@/hooks/use-live-runners";

const badgeEmoji=["🏁","⚡","🔟","🌙","👥","🏆","🌅","50","100","🔥","👑"];
export function PlayerProfile({publicView=false,username=""}:{publicView?:boolean;username?:string}){
  const router=useRouter(),{state,toggleFollow,notify}=useGame(),{runners,loading}=useLiveRunners(),runner=useMemo(()=>runners.find(r=>r.username===username),[runners,username]),id=runner?.id??"",following=Boolean(id&&state.followedRunnerIds.includes(id)),name=publicView?(runner?.name??username):state.profile.displayName,avatar=publicView?(runner?.avatar??"🏃"):state.profile.avatar,level=publicView?(runner?.level??1):state.profile.level,totalKm=publicView?0:state.runs.reduce((sum,run)=>sum+run.distanceKm,0),unlocked=publicView?[]:state.achievements,tier=rankForRp(state.seasonState.rp);
  async function share(){const text=`Check out ${name}'s RUN QUEST profile!`;try{if(navigator.share)await navigator.share({title:"RUN QUEST profile",text});else{await navigator.clipboard.writeText(text);notify("Profile link copied")}}catch{notify("Sharing cancelled")}}
  if(publicView&&loading)return <div className="skeleton h-80 rounded-3xl"/>;if(publicView&&!runner)return <div className="panel p-8 text-center"><b>RUNNER NOT FOUND</b><p className="muted mt-2 text-xs">This profile does not exist or is private.</p></div>;return <div>
    <section className="relative overflow-hidden rounded-[1.8rem] bg-gradient-to-br from-[#7c42ff] to-[#4011aa] p-6 md:p-8"><div className="relative flex flex-col items-center gap-5 text-center sm:flex-row sm:text-left"><span className="relative grid size-24 place-items-center rounded-full border-4 border-[#b7ff22] bg-[#a189d8] text-6xl">{avatar}<i className="absolute -bottom-1 -right-1 grid size-8 place-items-center rounded-full bg-[#b7ff22] text-[.58rem] font-black not-italic text-[#111]">{level}</i></span><div className="flex-1"><p className="text-[.55rem] font-black text-[#d5c7f7]">LIFETIME PLAYER PROFILE</p><h1 className="game-title mt-2 text-4xl">{name.toUpperCase()}</h1><p className="mt-2 text-[.62rem] font-black text-[#d1c3f3]">LV.{level} CITY RUNNER • VIENTIANE</p><div className="mt-4 max-w-md"><div className="flex justify-between text-[.5rem] font-black"><span className="text-[#b7ff22]">LEVEL {level}</span><span>{state.profile.totalXp.toLocaleString()} XP</span></div><div className="mt-2 h-2 rounded-full bg-black/20"><i className="block h-full rounded-full bg-[#b7ff22]" style={{width:`${state.profile.totalXp%500/5}%`}}/></div></div></div><button onClick={publicView?()=>{toggleFollow(id);notify(following?"Runner unfollowed":"Runner followed")}:share} className="ghost-button relative !bg-white/10"><Share2 size={15}/>{publicView?(following?"FOLLOWING":"FOLLOW"):"SHARE PROFILE"}</button></div></section>
    <section className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-5">{[[totalKm.toFixed(1),"LIFETIME KM"],[String(state.runs.length),"TOTAL RUNS"],[String(state.completedQuestIds.length),"QUESTS"],[String(unlocked.length),"BADGES"],[`🔥 ${state.profile.streak}`,"DAY STREAK"]].map(item=><div key={item[1]} className="panel p-4 text-center"><b className="block text-2xl">{item[0]}</b><small className="mt-1 block text-[.48rem] font-black text-[#818598]">{item[1]}</small></div>)}</section>
    {!publicView&&<><section className="game-shape mt-6 rounded-[2rem_2rem_1rem_2rem] bg-[#7439ee] p-5"><div className="flex items-center gap-4"><span className="grid size-16 place-items-center rounded-2xl bg-[#b6ff22] text-3xl text-[#171720]">{tier.icon}</span><span className="flex-1"><p className="text-[.5rem] font-black tracking-[.15em] text-[#dacdff]">CURRENT SEASON</p><h2 className="mt-1 text-xl font-black">{rankLabel(tier)} • {state.seasonState.rp.toLocaleString()} RP</h2><p className="mt-1 text-[.52rem] font-black text-[#dacdff]">{state.seasonState.leaderboardPosition>0?`#${state.seasonState.leaderboardPosition} OVERALL`:"UNRANKED"} • SEASON QUEST {state.seasonState.completedQuestIds.length}/6</p></span><Trophy className="text-[#b6ff22]"/></div></section><section className="panel mt-6 p-5"><p className="eyebrow">SEASON HISTORY</p><div className="mt-4 grid gap-2">{state.seasonHistory.length?state.seasonHistory.map(record=>{const past=rankTiers.find(t=>t.id===record.finalRankTierId)??rankTiers[0];return <div key={record.seasonId} className="flex items-center gap-3 rounded-2xl bg-[#242632] p-4"><span className="text-2xl">{past.icon}</span><span className="flex-1"><b className="block text-xs">{record.label}</b><small className="text-[.5rem] font-black text-[#85899b]">{rankLabel(past)} • {record.leaderboardPosition>0?`#${record.leaderboardPosition}`:"UNRANKED"} • {record.distanceKm} KM</small></span>{record.badge&&<span className="text-xl">🏅</span>}</div>}):<p className="muted text-xs">No completed season history yet.</p>}</div></section></>}
    <section className="panel mt-6 p-5 md:p-7"><div className="flex justify-between"><div><p className="eyebrow">LIFETIME COLLECTION</p><h2 className="mt-1 text-xl font-black">ACHIEVEMENTS</h2></div><span className="text-[.55rem] font-black text-[#7f8396]">{unlocked.length} / {allAchievements.length}</span></div><div className="mt-6 grid grid-cols-2 gap-2 sm:grid-cols-5">{allAchievements.map((achievement,index)=><div key={achievement} className={`rounded-2xl bg-[#1e2033] p-4 text-center ${!unlocked.includes(achievement)?"grayscale opacity-30":""}`}><span className="grid h-14 place-items-center text-3xl">{unlocked.includes(achievement)?badgeEmoji[index]:"🔒"}</span><b className="mt-2 block text-[.55rem]">{achievement}</b></div>)}</div></section>
    {publicView&&<section className="mt-5 grid grid-cols-2 gap-3"><button onClick={()=>router.push(`/match?runner=${id}`)} className="lime-button">INVITE TO QUEST</button><button onClick={()=>router.push(`/safety?runner=${id}`)} className="ghost-button"><ShieldCheck size={15}/>REPORT / BLOCK</button></section>}
  </div>
}
