import { questTemplates } from "./templates";
import type { DailyPlayerState,PersonalizationContext,QuestAssignment,QuestAssignmentType,QuestTemplate,RunnerDNA } from "@/types/personalization";
const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));
const round=(n:number,step=.5)=>Math.round(n/step)*step;
const dayMs=86_400_000;
function hash(text:string){let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function seededIndex(seed:string,length:number){return length?hash(seed)%length:0}
export function determineDailyPlayerState(c:PersonalizationContext):DailyPlayerState{const m=c.metrics;if(m.daysSinceLastRun!==null&&m.daysSinceLastRun>=14)return "RETURNING";if(c.dna.recoveryNeed>=65||m.hardRunsLast7Days>=3)return "RECOVERY";if(m.runsLast7Days>=6)return "HIGH_ACTIVITY";if(m.questCompletionRate>=.8&&m.runsLast30Days>=6&&c.dna.recoveryNeed<35)return "READY_FOR_CHALLENGE";if(m.runsLast7Days>=c.dna.weeklyTargetRuns)return "ACTIVE";return "NORMAL"}
export function calculateQuestDifficulty(t:QuestTemplate,distanceKm:number,paceTarget:number|null,checkpoints:number){const distance=distanceKm/2,pace=paceTarget?clamp((480-paceTarget)/35,0,3):0,checkpoint=checkpoints*.35,social=t.social?.5:0,pressure=t.pacePressure==="target"?1.4:t.pacePressure==="light"?.5:0;return Number(clamp(distance+pace+checkpoint+social+pressure,1,10).toFixed(1))}
function isCoolingDown(t:QuestTemplate,c:PersonalizationContext){const cutoff=new Date(c.now).getTime()-t.cooldownDays*dayMs;return c.history.some(h=>h.templateId===t.templateId&&new Date(h.assignedAt).getTime()>cutoff)}
export function scoreQuestTemplate(t:QuestTemplate,c:PersonalizationContext,state=determineDailyPlayerState(c)){const dna=c.dna,ability=1-Math.min(1,Math.abs(t.difficulty-dna.difficultyTier)/7),goal=t.goals.includes(dna.goal)?1:.25,distance=1-Math.min(1,Math.abs((t.distanceRangeKm[0]+t.distanceRangeKm[1])/2-dna.preferredDistanceKm)/10),recentActivity=state==="RECOVERY"||state==="RETURNING"?t.type==="recovery"||t.type==="returning"?1:.1:t.type==="recovery"?.2:1,preference=dna.preferredQuestTypes.includes(t.type)||t.goals.some(g=>dna.preferredQuestTypes.includes(g))?1:.35,time=t.preferredTimes?.includes(dna.preferredTime)?1:t.preferredTimes?.length?.4:.7,social=t.social?dna.socialScore/100:1-dna.socialScore/150,recentCategories=c.history.slice(0,2).map(h=>h.questType),variety=recentCategories.filter(x=>x===t.type).length>=2?.1:recentCategories[0]===t.type?.55:1;return Math.round(clamp((ability*.25+goal*.20+distance*.15+recentActivity*.15+preference*.10+time*.05+social*.05+variety*.05)*100,0,100))}
function targetDistance(t:QuestTemplate,dna:RunnerDNA,state:DailyPlayerState,availability:number){let target=clamp(dna.preferredDistanceKm,t.distanceRangeKm[0],t.distanceRangeKm[1]);if(state==="RECOVERY"||state==="RETURNING"||state==="HIGH_ACTIVITY")target*=.7;if(state==="READY_FOR_CHALLENGE")target*=1.12;target=Math.min(target,availability/(dna.avgPaceSecPerKm/60));return round(clamp(target,t.distanceRangeKm[0],t.distanceRangeKm[1]))}
export function customizeQuest(t:QuestTemplate,c:PersonalizationContext,assignmentType:QuestAssignmentType):QuestAssignment{const state=determineDailyPlayerState(c),distance=targetDistance(t,c.dna,state,c.availabilityMinutes),ratio=(distance-t.distanceRangeKm[0])/Math.max(1,t.distanceRangeKm[1]-t.distanceRangeKm[0]),checkpoints=Math.round(t.checkpointRange[0]+ratio*(t.checkpointRange[1]-t.checkpointRange[0])),pace=t.pacePressure==="none"?null:Math.round(c.dna.avgPaceSecPerKm*(t.pacePressure==="target"?.97:1.06)),score=scoreQuestTemplate(t,c,state),difficultyScore=calculateQuestDifficulty(t,distance,pace,checkpoints),reward=Math.round((t.xpBase+distance*35+checkpoints*20)*(assignmentType==="bonus"?.55:1)/10)*10,title=t.titleVariants[seededIndex(`${c.userId}:${c.now.slice(0,10)}:${t.templateId}`,t.titleVariants.length)],why=[`Matches your usual ${Math.max(1,distance-.5)}–${distance+.5} KM range`,t.preferredTimes?.includes(c.dna.preferredTime)?`Fits your ${c.dna.preferredTime} running time`:`Fits your ${c.dna.goal} goal`,state==="READY_FOR_CHALLENGE"?"Your recent runs show you are ready for more":state==="RECOVERY"?"Keeps today lighter after recent activity":`${score}% match with your Runner DNA`];return{id:`${c.userId}-${c.now.slice(0,10)}-${assignmentType}-${t.templateId}`,templateId:t.templateId,generatedTitle:title,questType:t.type,difficulty:t.difficulty,difficultyScore,targetDistanceKm:distance,targetPaceSecPerKm:pace,checkpointCount:checkpoints,rewardXp:reward,partySize:t.social?[2,4]:null,assignmentType,assignedAt:c.now,expiresAt:new Date(new Date(c.now).getTime()+dayMs).toISOString(),status:"assigned",personalizationScore:score,why,generationMetadata:{playerState:state,world:c.currentWorld,dnaVersion:c.dna.updatedAt,engineVersion:"1.0.0"}}}
export function generateDailyQuests(c:PersonalizationContext,templates=questTemplates):QuestAssignment[]{const state=determineDailyPlayerState(c),eligible=templates.filter(t=>t.minLevel<=c.level&&!c.excludedTemplateIds?.includes(t.templateId)).filter(t=>!isCoolingDown(t,c)||t.type==="recovery").filter(t=>state==="RETURNING"?t.type==="returning"||t.type==="recovery":state==="RECOVERY"?t.difficulty<=3:t.type!=="returning").sort((a,b)=>scoreQuestTemplate(b,c,state)-scoreQuestTemplate(a,c,state)||a.templateId.localeCompare(b.templateId));const primary=(state==="RETURNING"?eligible.find(t=>t.type==="returning"):state==="RECOVERY"?eligible.find(t=>t.type==="recovery"):eligible[0])??eligible[0]??templates[0],bonus=eligible.find(t=>t.templateId!==primary.templateId&&t.social!==primary.social)??eligible.find(t=>t.templateId!==primary.templateId)??templates[1],out=[customizeQuest(primary,c,"primary"),customizeQuest(bonus,c,"bonus")];if((state==="RECOVERY"||state==="HIGH_ACTIVITY")&&!out.some(q=>q.questType==="recovery")){const recovery=templates.find(t=>t.type==="recovery");if(recovery)out.push(customizeQuest(recovery,c,"recovery"))}return out}
export function selectCommunityQuest(c:PersonalizationContext,templates=questTemplates){const t=templates.find(x=>x.community);return t?customizeQuest(t,c,"community"):null}
