import type { SupabaseClient } from "@supabase/supabase-js";
import type { BehaviorMetrics,PersonalizationContext,QuestAssignment,QuestHistoryItem,RunnerDNA } from "@/types/personalization";
import { questionnaireToDNA } from "./runner-dna";
const fallbackDNA=()=>questionnaireToDNA({frequency:"1-2",comfortableDistance:"3-5",pace:"unknown",goal:"health",preferredTime:"evening",social:"sometimes",style:"fitness",availabilityMinutes:45});
const fallbackMetrics:BehaviorMetrics={runsLast7Days:0,runsLast30Days:0,distanceLast7Days:0,distanceLast30Days:0,avgPaceLast30Days:null,avgDistanceLast30Days:null,questCompletionRate:.5,failedQuestRate:0,abandonedRuns:0,socialRunRatio:0,hardRunsLast7Days:0,daysSinceLastRun:null,mostUsedQuestType:"distance",streakDays:0};
export const dnaFromRow=(r:Record<string,unknown>):RunnerDNA=>({experience:String(r.experience_level||"beginner") as RunnerDNA["experience"],avgPaceSecPerKm:Number(r.avg_pace_sec_per_km||435),preferredDistanceKm:Number(r.preferred_distance_km||3),difficultyTier:Number(r.difficulty_tier||2),goal:String(r.main_goal||"health") as RunnerDNA["goal"],preferredTime:String(r.preferred_time||"evening") as RunnerDNA["preferredTime"],preferredQuestTypes:(r.preferred_quest_types as string[])||[],socialScore:Number(r.social_score||50),competitiveScore:Number(r.competition_score||30),explorationScore:Number(r.exploration_score||50),consistencyScore:Number(r.consistency_score||50),weeklyTargetRuns:Number(r.weekly_target_runs||3),typicalRunDurationMinutes:Number(r.typical_run_duration_minutes||45),recentActivityLevel:Number(r.recent_activity_level||0),recoveryNeed:Number(r.recovery_need||0),streakBehavior:Number(r.streak_behavior||0),questCompletionRate:Number(r.quest_completion_rate||.5),confidence:(r.confidence as Record<string,number>)||{},archetype:String(r.archetype||"ALL-ROUNDER") as RunnerDNA["archetype"],updatedAt:String(r.updated_at||new Date().toISOString())});
const metricsFromRow=(r:Record<string,unknown>):BehaviorMetrics=>({runsLast7Days:Number(r.runs_last_7_days||0),runsLast30Days:Number(r.runs_last_30_days||0),distanceLast7Days:Number(r.distance_last_7_days||0),distanceLast30Days:Number(r.distance_last_30_days||0),avgPaceLast30Days:r.avg_pace_last_30_days==null?null:Number(r.avg_pace_last_30_days),avgDistanceLast30Days:r.avg_distance_last_30_days==null?null:Number(r.avg_distance_last_30_days),questCompletionRate:Number(r.quest_completion_rate||0),failedQuestRate:Number(r.failed_quest_rate||0),abandonedRuns:Number(r.abandoned_runs||0),socialRunRatio:Number(r.social_run_ratio||0),hardRunsLast7Days:Number(r.hard_runs_last_7_days||0),daysSinceLastRun:r.days_since_last_run==null?null:Number(r.days_since_last_run),mostUsedQuestType:String(r.most_used_quest_type||"distance"),streakDays:Number(r.streak_days||0)});
export async function loadPersonalizationContext(client:SupabaseClient,userId:string,now=new Date().toISOString()):Promise<PersonalizationContext>{const [{data:profile},{data:dnaRow},{data:metricRow},{data:historyRows},{data:daily}]=await Promise.all([client.from("profiles").select("level").eq("id",userId).maybeSingle(),client.from("runner_dna").select("*").eq("user_id",userId).maybeSingle(),client.from("runner_behavior_metrics").select("*").eq("user_id",userId).maybeSingle(),client.from("user_quest_assignments").select("quest_template_id,status,assigned_at,completed_at,quest_type,difficulty").eq("user_id",userId).order("assigned_at",{ascending:false}).limit(50),client.from("daily_player_state").select("available_minutes").eq("user_id",userId).eq("state_date",now.slice(0,10)).maybeSingle()]);const dna=dnaRow?dnaFromRow(dnaRow):fallbackDNA(),metrics=metricRow?metricsFromRow(metricRow):fallbackMetrics,history:QuestHistoryItem[]=(historyRows||[]).map(r=>({templateId:r.quest_template_id,status:r.status,assignedAt:r.assigned_at,completedAt:r.completed_at||undefined,questType:r.quest_type,difficulty:r.difficulty}));return{userId,level:profile?.level||1,now,dna,metrics,history,availabilityMinutes:daily?.available_minutes||dna.typicalRunDurationMinutes,currentWorld:"world-2"}}
export function assignmentToRow(userId:string,a:QuestAssignment){return{id:a.id,user_id:userId,quest_template_id:a.templateId,generated_title:a.generatedTitle,quest_type:a.questType,difficulty:a.difficulty,difficulty_score:a.difficultyScore,target_distance_km:a.targetDistanceKm,target_pace_sec_per_km:a.targetPaceSecPerKm,checkpoint_count:a.checkpointCount,reward_xp:a.rewardXp,party_size_min:a.partySize?.[0]??null,party_size_max:a.partySize?.[1]??null,assignment_type:a.assignmentType,assigned_at:a.assignedAt,expires_at:a.expiresAt,status:a.status,personalization_score:a.personalizationScore,why_reasons:a.why,generation_metadata:a.generationMetadata}}
export async function persistAssignments(client:SupabaseClient,userId:string,assignments:QuestAssignment[]){const {error}=await client.from("user_quest_assignments").upsert(assignments.map(a=>assignmentToRow(userId,a)));if(error)throw error}
export function assignmentFromRow(r:Record<string,unknown>):QuestAssignment{return{id:String(r.id),templateId:String(r.quest_template_id),generatedTitle:String(r.generated_title),questType:String(r.quest_type),difficulty:Number(r.difficulty),difficultyScore:Number(r.difficulty_score),targetDistanceKm:Number(r.target_distance_km),targetPaceSecPerKm:r.target_pace_sec_per_km==null?null:Number(r.target_pace_sec_per_km),checkpointCount:Number(r.checkpoint_count),rewardXp:Number(r.reward_xp),partySize:r.party_size_min==null?null:[Number(r.party_size_min),Number(r.party_size_max)],assignmentType:String(r.assignment_type) as QuestAssignment["assignmentType"],assignedAt:String(r.assigned_at),expiresAt:String(r.expires_at),status:String(r.status) as QuestAssignment["status"],personalizationScore:Number(r.personalization_score),why:(r.why_reasons as string[])||[],generationMetadata:(r.generation_metadata as Record<string,unknown>)||{}}}
