import type { BehaviorMetrics,RunnerArchetype,RunnerDNA,RunnerQuestionnaire } from "@/types/personalization";
const paceMap:Record<RunnerQuestionnaire["pace"],number>={unknown:435,"8+":510,"7-8":450,"6-7":390,"5-6":330,"under-5":285};
const distanceMap:Record<RunnerQuestionnaire["comfortableDistance"],number>={"1-3":2.5,"3-5":4,"5-10":7.5,"10+":12};
const frequencyMap:Record<RunnerQuestionnaire["frequency"],number>={starting:2,"1-2":2,"3-4":4,"5+":6};
const socialMap:Record<RunnerQuestionnaire["social"],number>={solo:15,sometimes:45,often:75,meet:95};
const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,n));
export function selectArchetype(d:Pick<RunnerDNA,"socialScore"|"competitiveScore"|"explorationScore"|"consistencyScore"|"goal"|"preferredTime"|"preferredDistanceKm">):RunnerArchetype{if(d.preferredTime==="night")return "NIGHT RUNNER";if(d.preferredDistanceKm>=10)return "ENDURANCE RUNNER";if(d.socialScore>=75)return "SOCIAL RUNNER";if(d.competitiveScore>=70||d.goal==="speed")return "SPEED HUNTER";if(d.explorationScore>=70)return "CITY EXPLORER";if(d.consistencyScore>=70)return "CONSISTENCY BUILDER";return "ALL-ROUNDER"}
export function questionnaireToDNA(q:RunnerQuestionnaire,now=new Date().toISOString()):RunnerDNA{const socialScore=socialMap[q.social],competitiveScore=q.goal==="competition"||q.goal==="speed"?85:q.style==="competitive"?70:30,explorationScore=q.goal==="exploration"||q.style==="adventure"?85:45,consistencyScore=q.goal==="consistency"?90:55;const experience:RunnerDNA["experience"]=q.frequency==="starting"?"beginner":q.frequency==="5+"?"advanced":"intermediate";const base={experience,avgPaceSecPerKm:paceMap[q.pace],preferredDistanceKm:distanceMap[q.comfortableDistance],difficultyTier:experience==="beginner"?2:experience==="advanced"?7:4,goal:q.goal,preferredTime:q.preferredTime,preferredQuestTypes:[q.style,q.goal],socialScore,competitiveScore,explorationScore,consistencyScore,weeklyTargetRuns:frequencyMap[q.frequency],typicalRunDurationMinutes:q.availabilityMinutes,recentActivityLevel:40,recoveryNeed:10,streakBehavior:50,questCompletionRate:.5,confidence:{avgPaceSecPerKm:q.pace==="unknown"?.15:.35,preferredDistanceKm:.35,goal:.4,preferredTime:.4},updatedAt:now};return{...base,archetype:selectArchetype(base)}}
export function updateRunnerDNA(current:RunnerDNA,metrics:BehaviorMetrics,now=new Date().toISOString()):RunnerDNA{const runConfidence=clamp(metrics.runsLast30Days/10,0,.9),blend=(reported:number,actual:number|null)=>actual==null?reported:Math.round(reported*(1-runConfidence)+actual*runConfidence),preferredDistanceKm=Number(blend(current.preferredDistanceKm,metrics.avgDistanceLast30Days).toFixed(1)),avgPaceSecPerKm=blend(current.avgPaceSecPerKm,metrics.avgPaceLast30Days),recentActivityLevel=clamp(metrics.runsLast7Days/Math.max(1,current.weeklyTargetRuns)*100),recoveryNeed=clamp(metrics.hardRunsLast7Days*22+metrics.abandonedRuns*8+(metrics.failedQuestRate>.4?20:0));const updated={...current,avgPaceSecPerKm,preferredDistanceKm,recentActivityLevel,recoveryNeed,streakBehavior:clamp(metrics.streakDays*8),questCompletionRate:metrics.questCompletionRate,socialScore:Math.round(current.socialScore*.7+metrics.socialRunRatio*100*.3),confidence:{...current.confidence,avgPaceSecPerKm:runConfidence,preferredDistanceKm:runConfidence},updatedAt:now};return{...updated,archetype:selectArchetype(updated)}}
