"use client";
import {useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";
import type {Coordinates,Runner} from "@/types/game";

type PreferenceRow={preferred_distance_min_km:number|null;preferred_distance_max_km:number|null;average_pace_min_km:number|null;experience_level:string|null;preferred_times:string[]|null;running_styles:string[]|null};
type ProfileRow={id:string;display_name:string;username:string;avatar_url:string|null;level:number;title:string;streak_days:number;runner_rating:number|null;runner_preferences:PreferenceRow|PreferenceRow[]|null};
type SignalRow={user_id:string;radius_km:number|null;approx_latitude:number|null;approx_longitude:number|null};
const preference=(value:ProfileRow["runner_preferences"])=>Array.isArray(value)?value[0]:value;
const distanceBetween=(a:Coordinates,b:Coordinates)=>{const toRad=Math.PI/180,dLat=(b.lat-a.lat)*toRad,dLng=(b.lng-a.lng)*toRad,q=Math.sin(dLat/2)**2+Math.cos(a.lat*toRad)*Math.cos(b.lat*toRad)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))};
const toRunner=(row:ProfileRow,distanceAwayKm=0):Runner=>{const pref=preference(row.runner_preferences);return{id:row.id,name:row.display_name,username:row.username,avatar:row.avatar_url||"🏃",level:Number(row.level||1),title:row.title||"ROOKIE",paceMinKm:Number(pref?.average_pace_min_km||7),distanceRange:[Number(pref?.preferred_distance_min_km||3),Number(pref?.preferred_distance_max_km||10)],streak:Number(row.streak_days||0),rating:Number(row.runner_rating||5),distanceAwayKm,availableTimes:pref?.preferred_times||[],experience:pref?.experience_level||"beginner",style:pref?.running_styles?.[0]||"casual",questTypes:[]}};

export function useLiveRunners(activeOnly=false,origin:Coordinates|null=null,searchRadius=10){
  const [runners,setRunners]=useState<Runner[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const lat=origin?.lat??null,lng=origin?.lng??null;
  const load=useCallback(async()=>{const client=createClient();if(!client){setError("Live database is not configured");setLoading(false);return}const {data:{user}}=await client.auth.getUser();if(!user){setError("Login required");setLoading(false);return}let ids:string[]|null=null,distances=new Map<string,number>();if(activeOnly){const {data,error:signalError}=await client.from("run_signals").select("user_id,radius_km,approx_latitude,approx_longitude").eq("status","active").gt("expires_at",new Date().toISOString());if(signalError){setError(signalError.message);setLoading(false);return}const compatible=((data||[]) as SignalRow[]).filter(row=>{if(row.user_id===user.id)return false;if(lat===null||lng===null||row.approx_latitude===null||row.approx_longitude===null)return false;const distance=distanceBetween({lat,lng},{lat:Number(row.approx_latitude),lng:Number(row.approx_longitude)});distances.set(row.user_id,distance);return distance<=Math.min(searchRadius,Number(row.radius_km||searchRadius))});ids=[...new Set(compatible.map(row=>row.user_id))];if(!ids.length){setRunners([]);setError("");setLoading(false);return}}let query=client.from("profiles").select("id,display_name,username,avatar_url,level,title,streak_days,runner_rating,runner_preferences(preferred_distance_min_km,preferred_distance_max_km,average_pace_min_km,experience_level,preferred_times,running_styles)").neq("id",user.id).eq("is_private",false).limit(50);if(ids)query=query.in("id",ids);const {data,error:profileError}=await query;if(profileError)setError(profileError.message);else{setRunners((data||[]).map(row=>toRunner(row as unknown as ProfileRow,distances.get(row.id)||0)).sort((a,b)=>a.distanceAwayKm-b.distanceAwayKm));setError("")}setLoading(false)},[activeOnly,lat,lng,searchRadius]);
  useEffect(()=>{void load();const client=createClient();if(!client)return;const channel=client.channel(`live-runners-${activeOnly}`).on("postgres_changes",{event:"*",schema:"public",table:activeOnly?"run_signals":"profiles"},()=>void load()).subscribe(),timer=activeOnly?window.setInterval(()=>void load(),15000):null;return()=>{if(timer)window.clearInterval(timer);void client.removeChannel(channel)}},[load,activeOnly]);
  return{runners,loading,error,reload:load};
}
