"use client";
import { useCallback,useEffect,useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { Runner } from "@/types/game";

type PreferenceRow={preferred_distance_min_km:number|null;preferred_distance_max_km:number|null;average_pace_min_km:number|null;experience_level:string|null;preferred_times:string[]|null;running_styles:string[]|null};
type ProfileRow={id:string;display_name:string;username:string;avatar_url:string|null;level:number;title:string;streak_days:number;runner_rating:number|null;runner_preferences:PreferenceRow|PreferenceRow[]|null};
const preference=(value:ProfileRow["runner_preferences"])=>Array.isArray(value)?value[0]:value;
const toRunner=(row:ProfileRow):Runner=>{const pref=preference(row.runner_preferences);return{id:row.id,name:row.display_name,username:row.username,avatar:row.avatar_url||"🏃",level:Number(row.level||1),title:row.title||"ROOKIE",paceMinKm:Number(pref?.average_pace_min_km||7),distanceRange:[Number(pref?.preferred_distance_min_km||3),Number(pref?.preferred_distance_max_km||10)],streak:Number(row.streak_days||0),rating:Number(row.runner_rating||5),distanceAwayKm:0,availableTimes:pref?.preferred_times||[],experience:pref?.experience_level||"beginner",style:pref?.running_styles?.[0]||"casual",questTypes:[]}};

export function useLiveRunners(activeOnly=false){const [runners,setRunners]=useState<Runner[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{const client=createClient();if(!client){setError("Live database is not configured");setLoading(false);return}const {data:{user}}=await client.auth.getUser();if(!user){setError("Login required");setLoading(false);return}let ids:string[]|null=null;if(activeOnly){const {data,error:signalError}=await client.from("run_signals").select("user_id").eq("status","active").gt("expires_at",new Date().toISOString());if(signalError){setError(signalError.message);setLoading(false);return}ids=[...new Set((data||[]).map(row=>row.user_id).filter(id=>id!==user.id))];if(!ids.length){setRunners([]);setLoading(false);return}}let query=client.from("profiles").select("id,display_name,username,avatar_url,level,title,streak_days,runner_rating,runner_preferences(preferred_distance_min_km,preferred_distance_max_km,average_pace_min_km,experience_level,preferred_times,running_styles)").neq("id",user.id).eq("is_private",false).limit(50);if(ids)query=query.in("id",ids);const {data,error:profileError}=await query;if(profileError)setError(profileError.message);else{setRunners((data||[]).map(row=>toRunner(row as unknown as ProfileRow)));setError("")}setLoading(false)},[activeOnly]);useEffect(()=>{void load();const client=createClient();if(!client)return;const channel=client.channel(`live-runners-${activeOnly}`).on("postgres_changes",{event:"*",schema:"public",table:activeOnly?"run_signals":"profiles"},()=>void load()).subscribe();return()=>{void client.removeChannel(channel)}},[load,activeOnly]);return{runners,loading,error,reload:load}}
