"use client";

import {useCallback,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase/client";

export type PartyInvite={partyId:string;ownerId:string;ownerName:string;ownerAvatar:string;ownerLevel:number;createdAt:string};

export function usePartyInvites(){
  const [invites,setInvites]=useState<PartyInvite[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{const client=createClient();if(!client){setError("Live database is unavailable");setLoading(false);return}const {data:{user}}=await client.auth.getUser();if(!user){setInvites([]);setLoading(false);return}const {data:members,error:memberError}=await client.from("party_members").select("party_id,joined_at").eq("user_id",user.id).eq("status","invited").order("joined_at",{ascending:false});if(memberError){setError(memberError.message);setLoading(false);return}const partyIds=(members||[]).map(row=>row.party_id);if(!partyIds.length){setInvites([]);setError("");setLoading(false);return}const {data:parties,error:partyError}=await client.from("parties").select("id,owner_id,created_at").in("id",partyIds).eq("status","forming");if(partyError){setError(partyError.message);setLoading(false);return}const ownerIds=[...new Set((parties||[]).map(row=>row.owner_id))];if(!ownerIds.length){setInvites([]);setError("");setLoading(false);return}const {data:owners,error:ownerError}=await client.from("profiles").select("id,display_name,avatar_url,level").in("id",ownerIds);if(ownerError){setError(ownerError.message);setLoading(false);return}const byOwner=new Map((owners||[]).map(row=>[row.id,row]));setInvites((parties||[]).map(row=>{const owner=byOwner.get(row.owner_id);return{partyId:row.id,ownerId:row.owner_id,ownerName:owner?.display_name||"Runner",ownerAvatar:owner?.avatar_url||"🏃",ownerLevel:Number(owner?.level||1),createdAt:row.created_at}}));setError("");setLoading(false)},[]);
  useEffect(()=>{void load();const client=createClient();if(!client)return;const channel=client.channel("my-party-invites").on("postgres_changes",{event:"*",schema:"public",table:"party_members"},()=>void load()).on("postgres_changes",{event:"*",schema:"public",table:"parties"},()=>void load()).subscribe(),timer=window.setInterval(()=>void load(),15000);return()=>{window.clearInterval(timer);void client.removeChannel(channel)}},[load]);
  const respond=useCallback(async(partyId:string,accept:boolean)=>{const client=createClient();if(!client)throw new Error("Live database is unavailable");const {data:{user}}=await client.auth.getUser();if(!user)throw new Error("Login required");const {error:updateError}=await client.from("party_members").update({status:accept?"ready":"declined"}).eq("party_id",partyId).eq("user_id",user.id).eq("status","invited");if(updateError)throw updateError;await load();return partyId},[load]);
  return{invites,loading,error,accept:(partyId:string)=>respond(partyId,true),decline:(partyId:string)=>respond(partyId,false),reload:load};
}
