"use client";
import { useEffect } from "react";
import { useRouter } from "next/navigation";
import { CalendarDays,Flag,Play,Radar,Trophy,Users } from "lucide-react";
import { useGame } from "@/components/state/game-provider";
import { rpRewards } from "@/data/season";

export function TodayQuestCard(){const {state,ensureDailyQuests,acceptPersonalQuest}=useGame(),router=useRouter();useEffect(()=>ensureDailyQuests(),[]);const quest=state.dailyQuests.find(q=>q.assignmentType==="primary");if(!quest)return <div className="skeleton mt-4 h-36 rounded-[2rem]"/>;const questId=quest.id;function choose(path:string){acceptPersonalQuest(questId);router.push(path)}return <section className="game-shape mt-4 rounded-[2rem_2rem_.8rem_2rem] border border-[#9ee313] bg-[#b6ff22] p-5 text-[#171720]"><div className="flex items-start justify-between"><span><small className="text-[.52rem] font-black tracking-[.15em]">TODAY&apos;S PERSONAL QUEST</small><h2 className="game-title mt-2 text-3xl">{quest.generatedTitle}</h2></span><span className="grid size-11 place-items-center rounded-full bg-[#171720] text-[#b6ff22]"><Flag size={19}/></span></div><div className="mt-4 flex flex-wrap gap-x-4 gap-y-1 text-[.58rem] font-black"><span>{quest.targetDistanceKm} KM</span><span>{quest.checkpointCount} CHECKPOINTS</span><span>+{quest.rewardXp} XP</span><span>+{rpRewards.daily} RP</span></div><button onClick={()=>choose("/run")} className="mt-4 flex min-h-14 w-full items-center justify-center gap-2 rounded-2xl bg-[#171720] px-3 text-xs font-black text-white"><Play size={17} fill="currentColor"/>START SOLO</button><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={()=>choose(`/match?quest=${questId}`)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[#7439ee] px-2 text-[.6rem] font-black text-white"><Users size={16}/>FIND RUNNER</button><button onClick={()=>choose(`/run-signal?quest=${questId}`)} className="flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[#59e0dc] px-2 text-[.6rem] font-black text-[#171720]"><Radar size={16}/>RUN SIGNAL</button></div></section>}

export function WeeklyAndEventCards(){const {state}=useGame(),weekly=state.weeklyChallenge,event=state.specialEvents.find(item=>item.active&&!state.completedEventIds.includes(item.id)),percent=Math.min(100,weekly.progressKm/weekly.targetKm*100);return <div className="mt-6 grid gap-3 sm:grid-cols-2"><section className="game-shape rounded-[.9rem_2rem_2rem_2rem] border border-[#3b3b4b] bg-[#282835] p-5"><CalendarDays className="text-[#59e0dc]"/><p className="mt-4 text-[.5rem] font-black tracking-[.15em] text-[#9b9bad]">THIS WEEK • FLEXIBLE REST DAYS</p><h3 className="mt-1 text-sm font-black">{weekly.title}</h3><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#3a3a49]"><i className="block h-full rounded-full bg-[#59e0dc]" style={{width:`${percent}%`}}/></div><div className="mt-2 flex justify-between text-[.55rem] font-black"><span>{weekly.progressKm.toFixed(1)} / {weekly.targetKm} KM</span><span className="text-[#59e0dc]">+{rpRewards.weekly} RP</span></div></section>{event&&<section className="game-shape rounded-[2rem_.9rem_2rem_2rem] border border-[#8454ef] bg-[#7439ee] p-5"><Trophy className="text-[#b6ff22]"/><p className="mt-4 text-[.5rem] font-black tracking-[.15em] text-[#d7cafa]">SPECIAL EVENT</p><h3 className="mt-1 text-sm font-black">{event.title}</h3><p className="mt-3 flex items-center gap-2 text-[.55rem] font-black text-[#e0d8f5]"><Users size={13}/>{event.joinedRunners.toLocaleString()} RUNNERS • {event.distanceKm} KM</p><p className="mt-2 text-[.55rem] font-black text-[#b6ff22]">+{rpRewards.event} RP • {event.badge}</p></section>}</div>}
