"use client";
import { useEffect,useState } from "react";
import { useParams,useRouter,useSearchParams } from "next/navigation";
import { AlertTriangle,Check,Flag,LocateFixed,LockKeyhole,Map,MapPin,Pause,Play,ShieldAlert,Square } from "lucide-react";
import { useRunTracker } from "@/hooks/use-run-tracker";
import { useGame } from "@/components/state/game-provider";
import { quests } from "@/data/game-content";
import { mainQuests } from "@/data/journey";
import { verifyRun } from "@/lib/game/verification";
import { personalizeSeasonQuest } from "@/lib/season/engine";
import { routeDistanceMeters } from "@/lib/game/public-route";
const fmt=(seconds:number)=>`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`;
const paceLabel=(pace:number)=>pace>0&&Number.isFinite(pace)?`${Math.floor(pace)}:${String(Math.round(pace%1*60)).padStart(2,"0")}`:"--:--";
export function LiveRun(){
  const tracker=useRunTracker(),router=useRouter(),searchParams=useSearchParams(),params=useParams<{id:string}>(),{state,startQuest,completeRun,notify}=useGame(),[ending,setEnding]=useState(false),locationMode=searchParams.get("mode")==="location";
  const assignment=state.dailyQuests.find(q=>q.id===params.id),mainQuest=mainQuests.find(q=>q.id===params.id),seasonQuest=params.id.startsWith("season-")?personalizeSeasonQuest(params.id,state.runnerDNA):null,baseQuest=quests.find(q=>q.id===params.id)??quests[6],distanceObjective=mainQuest?.objectives.find(o=>o.kind==="distance"),checkpointObjective=mainQuest?.objectives.find(o=>o.kind==="checkpoint");
  const targetDistance=assignment?.targetDistanceKm??seasonQuest?.distanceKm??distanceObjective?.target??baseQuest.distanceKm,totalCheckpoints=locationMode?(assignment?.checkpointCount??seasonQuest?.checkpoints??checkpointObjective?.target??baseQuest.checkpoints.length):0,rewardXp=assignment?.rewardXp??seasonQuest?.xpReward??mainQuest?.xpReward??baseQuest.xp,officialCheckpoints=baseQuest.checkpoints.slice(0,totalCheckpoints),venueReached=Boolean(baseQuest.venue&&tracker.points.some(point=>routeDistanceMeters(point,baseQuest.venue!)<=baseQuest.venue!.radiusMeters)),reached=locationMode?officialCheckpoints.filter(checkpoint=>tracker.points.some(point=>routeDistanceMeters(point,checkpoint)<=checkpoint.radiusMeters)).length:0;
  const progress=Math.min(1,targetDistance?tracker.distanceKm/targetDistance:0),liveXp=Math.round(rewardXp*progress);
  useEffect(()=>{startQuest(params.id);tracker.start()},[]);
  useEffect(()=>{window.history.pushState({runLocked:true},"",window.location.href);const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue=""},keepRunOpen=()=>{window.history.pushState({runLocked:true},"",window.location.href);notify("Finish the run before leaving this screen")};window.addEventListener("beforeunload",warn);window.addEventListener("popstate",keepRunOpen);return()=>{window.removeEventListener("beforeunload",warn);window.removeEventListener("popstate",keepRunOpen)}},[notify]);
  function finish(){
    tracker.end();
    let verification=verifyRun(tracker.points);if(locationMode&&(!venueReached||reached<totalCheckpoints))verification={...verification,score:Math.min(verification.score,60),verified:false,flags:[...verification.flags,!venueReached?`Run did not enter ${baseQuest.venue?.name??"official venue"}`:`Only ${reached}/${totalCheckpoints} location checkpoints reached`]};const earnedXp=verification.verified?liveXp:0,runId=crypto.randomUUID();
    completeRun({id:runId,questId:params.id,distanceKm:Number(tracker.distanceKm.toFixed(3)),elapsedSeconds:tracker.elapsed,pace:paceLabel(tracker.pace),checkpoints:reached,totalCheckpoints,trustScore:verification.score,xp:earnedXp,partySize:Math.max(1,state.partyReady.filter(Boolean).length),exploredNewRoute:tracker.points.length>=3,route:tracker.points});
    router.replace(`/results/${runId}`);
  }
  const gpsText=tracker.gpsStatus==="active"?`${tracker.points.length} GPS POINTS`:tracker.gpsStatus==="requesting"?"CONNECTING TO GPS…":tracker.gpsStatus==="insecure"?"HTTPS REQUIRED FOR GPS":tracker.gpsStatus==="denied"?"LOCATION PERMISSION DENIED":tracker.gpsStatus==="unavailable"?"GPS UNAVAILABLE":"WAITING FOR GPS",gpsNeedsHelp=["insecure","denied","unavailable","error"].includes(tracker.gpsStatus);
  return <div className="mobile-page mx-auto flex min-h-[calc(100vh-72px)] max-w-2xl flex-col px-4 py-5 md:px-8">
    <div className="flex items-center justify-between"><span className={`rounded-lg px-3 py-2 text-[.55rem] font-black tracking-widest ${locationMode?"bg-[#2b2242] text-[#c6adff]":"bg-[#20363a] text-[#59e0dc]"}`}>{locationMode?`📍 ${baseQuest.venue?.name??"LOCATION QUEST"}`:"🏃 ANYWHERE • DISTANCE MODE"}</span><span className="flex items-center gap-2 rounded-xl border border-[#513b3b] bg-[#2b1e24] px-3 py-2 text-[.55rem] font-black text-[#ff8b72]"><ShieldAlert size={14}/>SAFETY ON</span></div>
    <div className="mt-[5vh] text-center"><p className="eyebrow">CURRENT DISTANCE</p><b className="game-title mt-2 block text-[5.1rem] text-[#b6ff22] md:text-[7rem]">{tracker.distanceKm.toFixed(2)} <small className="text-xl">KM</small></b>{gpsNeedsHelp?<button onClick={tracker.retryGps} className="ghost-button mx-auto mt-3 !min-h-10 border-[#b85a3f] text-[#b64529]"><LocateFixed size={14}/>{gpsText} • RETRY</button>:<span className="status-chip mt-3"><LocateFixed size={13} className={tracker.gpsStatus==="active"?"text-[#59e0dc]":"text-[#b56a00]"}/>{gpsText}</span>}</div>
    <div className="mt-7 grid grid-cols-3 border-y border-[#303348] py-5 text-center"><Stat label="PACE" value={paceLabel(tracker.pace)} note="/ KM"/><Stat label="TIME" value={fmt(tracker.elapsed)}/><Stat label="XP" value={`+${liveXp}`}/></div>
    {locationMode?<div className="mt-10 px-5"><div className="relative h-1.5 bg-[#303347]"><i className="absolute h-full bg-[#b7ff22]" style={{width:`${totalCheckpoints?reached/totalCheckpoints*100:0}%`}}/>{Array.from({length:totalCheckpoints},(_,i)=><Step key={i} pos={`${totalCheckpoints===1?100:i/(totalCheckpoints-1)*100}%`} done={i<reached} active={i===reached&&reached<totalCheckpoints} finish={i===totalCheckpoints-1} label={i===totalCheckpoints-1?"FINISH":`CP${i+1}`}/>)}</div></div>:<div className="mt-8 rounded-2xl border border-[#3a5a5f] bg-[#1c3035] p-4 text-center text-[.58rem] font-black text-[#59e0dc]">ANYWHERE MODE • COMPLETE THE GPS DISTANCE TO FINISH</div>}
    <div className={`panel flex items-center gap-3 p-4 ${locationMode?"mt-14":"mt-4"}`}><span className="grid size-12 place-items-center rounded-xl bg-[#b7ff22] text-[#111]"><MapPin size={21}/></span><span className="flex-1"><small className="block text-[.48rem] font-black text-[#7e8295]">{locationMode?"OFFICIAL LOCATION TARGET":"ANYWHERE TARGET"}</small><b className="mt-1 block text-xs">{targetDistance.toFixed(1)} KM{locationMode?` • ${reached}/${totalCheckpoints} CHECKPOINTS`:" • NO LOCATION REQUIRED"}</b><small className={`mt-1 block text-[.52rem] font-black ${locationMode&&!venueReached?"text-[#ff9b73]":"text-[#b7ff22]"}`}>{locationMode&&!venueReached?`GO TO ${baseQuest.venue?.name}`:`${Math.max(0,targetDistance-tracker.distanceKm).toFixed(2)} KM REMAINING`}</small></span><Map className="text-[#85899c]"/></div>
    <div className="mt-auto grid grid-cols-[1fr_1.5fr] gap-2 pt-7"><button onClick={tracker.pause} className="ghost-button">{tracker.status==="paused"?<Play size={17}/>:<Pause size={17}/>} {tracker.status==="paused"?"RESUME":"PAUSE"}</button><button onClick={()=>setEnding(true)} className="lime-button"><Square size={15} fill="currentColor"/>END RUN</button></div>
    {ending&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-5 backdrop-blur-lg"><div className="panel max-w-sm p-6 text-center"><AlertTriangle className="mx-auto text-[#ff8157]" size={35}/><h2 className="game-title mt-4 text-3xl">END THIS RUN?</h2><p className="muted mt-3 text-xs">Recorded: {tracker.distanceKm.toFixed(2)} KM from {tracker.points.length} GPS points. Runs without enough GPS samples will not receive verified XP.</p><div className="mt-6 grid grid-cols-2 gap-2"><button onClick={()=>setEnding(false)} className="ghost-button">KEEP RUNNING</button><button onClick={finish} className="lime-button">FINISH</button></div></div></div>}
  </div>
}
function Stat({label,value,note}:{label:string;value:string;note?:string}){return <span className="border-r border-[#303348] last:border-0"><small className="block text-[.5rem] font-black text-[#7f8396]">{label}</small><b className="mt-2 block text-2xl">{value}</b>{note&&<small className="text-[.5rem] text-[#7e8295]">{note}</small>}</span>}
function Step({pos,label,done,active,finish}:{pos:string;label:string;done?:boolean;active?:boolean;finish?:boolean}){return <span className={`absolute top-1/2 grid -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-[3px] border-[#0b0d19] ${active?"size-9 bg-white text-[#111]":"size-6"} ${done?"bg-[#b7ff22] text-[#111]":"bg-[#34374a] text-[#85899b]"}`} style={{left:pos}}>{done?<Check size={11}/>:active?<MapPin size={15}/>:finish?<Flag size={12}/>:<LockKeyhole size={9}/>}<i className="absolute top-8 whitespace-nowrap text-[.48rem] font-black not-italic text-[#777b8e]">{label}</i></span>}
