"use client";

import Link from "next/link";
import {useParams,useRouter} from "next/navigation";
import {Check,Radio,Users} from "lucide-react";
import {useCallback,useEffect,useRef,useState} from "react";
import {useGame} from "@/components/state/game-provider";
import {createClient} from "@/lib/supabase/client";

type Member={userId:string;name:string;avatar:string;level:number;totalXp:number;status:string};
type MemberRow={user_id:string;status:string;profiles:{display_name?:string;avatar_url?:string|null;level?:number;total_xp?:number}|{display_name?:string;avatar_url?:string|null;level?:number;total_xp?:number}[]|null};

export function PartyLobby(){
  const params=useParams<{id:string}>(),router=useRouter(),{state,notify}=useGame(),[members,setMembers]=useState<Member[]>([]),[ownerId,setOwnerId]=useState(""),[partyStatus,setPartyStatus]=useState("forming"),[startsAt,setStartsAt]=useState(""),[userId,setUserId]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[saving,setSaving]=useState(false),[now,setNow]=useState(Date.now()),navigating=useRef(false);
  const runHref=`/run/${state.activeQuestId||"free-run"}?party=${params.id}`,remainingMs=startsAt?new Date(startsAt).getTime()-now:0,countdown=Math.max(0,Math.ceil(remainingMs/1000));
  const load=useCallback(async()=>{const client=createClient();if(!client){setError("Live database is unavailable");setLoading(false);return}const {data:{user}}=await client.auth.getUser();if(!user){setError("Login required");setLoading(false);return}setUserId(user.id);const [{data:party,error:partyError},{data:rows,error:memberError}]=await Promise.all([client.from("parties").select("owner_id,status,starts_at").eq("id",params.id).maybeSingle(),client.from("party_members").select("user_id,status,profiles(display_name,avatar_url,level,total_xp)").eq("party_id",params.id).order("joined_at")]);if(partyError||memberError||!party){setError(partyError?.message||memberError?.message||"Party not found");setLoading(false);return}setOwnerId(party.owner_id);setPartyStatus(party.status);setStartsAt(party.starts_at||"");setMembers((rows||[]).filter(row=>row.status!=="declined").map(row=>{const typed=row as unknown as MemberRow,profile=Array.isArray(typed.profiles)?typed.profiles[0]:typed.profiles;return{userId:typed.user_id,name:profile?.display_name||"Runner",avatar:profile?.avatar_url||"🏃",level:Number(profile?.level||1),totalXp:Number(profile?.total_xp||0),status:typed.status}}));setError("");setLoading(false)},[params.id]);

  useEffect(()=>{void load();const client=createClient();if(!client)return;const channel=client.channel(`party-${params.id}`).on("postgres_changes",{event:"*",schema:"public",table:"party_members",filter:`party_id=eq.${params.id}`},()=>void load()).on("postgres_changes",{event:"UPDATE",schema:"public",table:"parties",filter:`id=eq.${params.id}`},()=>void load()).subscribe(),timer=window.setInterval(()=>void load(),3000);return()=>{window.clearInterval(timer);void client.removeChannel(channel)}},[load,params.id]);
  useEffect(()=>{if(partyStatus!=="active"||!startsAt)return;const timer=window.setInterval(()=>setNow(Date.now()),100);return()=>window.clearInterval(timer)},[partyStatus,startsAt]);
  useEffect(()=>{if(partyStatus==="active"&&startsAt&&remainingMs<=0&&!navigating.current){navigating.current=true;router.replace(runHref)}},[partyStatus,startsAt,remainingMs,router,runHref]);

  async function toggleReady(){const client=createClient(),self=members.find(member=>member.userId===userId);if(!client||!userId||!self||partyStatus!=="forming")return;setSaving(true);const {error:updateError}=await client.from("party_members").update({status:self.status==="ready"?"not_ready":"ready"}).eq("party_id",params.id).eq("user_id",userId);setSaving(false);if(updateError)notify(updateError.message);else void load()}
  async function start(){const client=createClient();if(!client)return;setSaving(true);const {data:startTime,error:startError}=await client.rpc("start_party_run",{p_party_id:params.id});setSaving(false);if(startError||!startTime){notify(startError?.message||"Could not start party");return}setPartyStatus("active");setStartsAt(String(startTime));setNow(Date.now())}

  if(partyStatus==="active"&&startsAt)return <div className={`fixed inset-0 z-[90] grid place-items-center ${countdown>0?"bg-[#090b18]":"bg-[#b7ff22] text-[#111]"}`}><div className="text-center"><p className="eyebrow">ALL RUNNERS READY</p><b className={`pop mt-3 block font-black ${countdown>0?"text-[11rem] text-[#b7ff22]":"text-[8rem]"}`}>{countdown>0?countdown:"GO!"}</b><p className="mt-4 text-xs font-black">STARTING ON EVERY DEVICE…</p></div></div>;
  if(loading)return <div className="skeleton h-72 rounded-3xl"/>;
  if(error)return <div className="panel p-7 text-center"><b>PARTY UNAVAILABLE</b><p className="muted mt-2 text-xs">{error}</p><Link href="/match" className="ghost-button mt-5">BACK TO RUNNERS</Link></div>;
  if(partyStatus==="active"&&!startsAt)return <div className="panel p-7 text-center"><b>PARTY RUN ALREADY ACTIVE</b><p className="muted mt-2 text-xs">This lobby was started before synchronized countdown was enabled.</p><Link href={runHref} className="lime-button mt-5">OPEN PARTY RUN</Link></div>;

  const self=members.find(member=>member.userId===userId),allReady=members.length>=2&&members.every(member=>member.status==="ready"),isOwner=ownerId===userId;
  return <div><div className="flex justify-center -space-x-3">{members.map(member=><span key={member.userId} className={`grid size-16 place-items-center rounded-full border-4 border-[#151727] text-4xl ${member.status==="ready"?"bg-[#b7ff22]":"bg-[#8f72d1]"}`}>{member.avatar}</span>)}</div><div className="mt-8 grid gap-2">{members.map(member=><div key={member.userId} className="panel flex items-center gap-3 p-3"><span className="grid size-12 place-items-center rounded-full bg-[#8f72d1] text-3xl">{member.avatar}</span><span className="flex-1"><b className="block text-xs">{member.name.toUpperCase()}</b><small className="text-[.5rem] font-black text-[#85899b]">LV.{member.level} • {member.totalXp.toLocaleString()} XP{member.userId===ownerId?" • PARTY LEADER":""}</small></span><span className={`rounded-lg px-2.5 py-2 text-[.5rem] font-black ${member.status==="ready"?"bg-[#29371c] text-[#b7ff22]":"bg-[#302f40] text-[#9da1b3]"}`}>{member.status==="ready"?<><Check className="mr-1 inline" size={11}/>READY</>:"NOT READY"}</span></div>)}</div><div className="mt-5 rounded-2xl border border-[#34374c] bg-[#1b1d2f] p-4"><div className="flex justify-between"><span><b className="block text-xs">{members.filter(member=>member.status==="ready").length} / {members.length} READY</b><small className="text-[.5rem] font-black text-[#7f8396]">{allReady?"EVERYONE READY • LEADER CAN START":"EVERY RUNNER MUST PRESS READY"}</small></span><Radio className={allReady?"text-[#b7ff22]":"text-[#74788c]"}/></div></div><button disabled={saving} onClick={()=>void toggleReady()} className={`mt-3 w-full disabled:opacity-50 ${self?.status==="ready"?"ghost-button":"lime-button"}`}>{self?.status==="ready"?"CANCEL READY":"I AM READY"}</button>{isOwner?<button disabled={!allReady||saving} onClick={()=>void start()} className="lime-button mt-3 w-full disabled:opacity-40"><Users size={17}/>{saving?"STARTING…":"START RUN FOR EVERYONE"}</button>:<p className="mt-4 text-center text-[.55rem] font-black text-[#85899b]">{allReady?"WAITING FOR PARTY LEADER TO START":"PRESS READY AND WAIT FOR THE LEADER"}</p>}<p className="mt-3 text-center text-[.5rem] font-black leading-4 text-[#8b8fa2]">เมื่อหัวหน้ากด Start ทุกเครื่องจะนับถอยหลังจากเวลาเดียวกันและเปิด GPS Run อัตโนมัติ</p><Link href="/match" className="ghost-button mt-3 w-full">BACK TO RUNNER MATCH</Link></div>
}
