"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { Check,Footprints,Gift,LockKeyhole,MapPin,Skull,Trophy } from "lucide-react";
import { useGame } from "@/components/state/game-provider";
import { seasonQuestBlueprints } from "@/data/season";
import { personalizeSeasonQuest } from "@/lib/season/engine";
import type { PersonalizedSeasonQuest } from "@/types/season";

function Node({quest,index,status,onStart}:{quest:PersonalizedSeasonQuest;index:number;status:"completed"|"active"|"available"|"locked";onStart:()=>void}){const right=index%2===0,locked=status==="locked",active=status==="active",Icon=quest.boss?Skull:status==="completed"?Footprints:status==="available"?Gift:MapPin;return <div className={`relative flex ${quest.boss?"min-h-48":"min-h-36"} items-center ${right?"justify-end pr-[4%]":"justify-start pl-[4%]"}`}><button disabled={!active} onClick={onStart} className={`relative z-10 flex items-center gap-3 text-left disabled:cursor-default ${right?"flex-row":"flex-row-reverse"}`}><div className={`relative grid place-items-center rounded-full border-[6px] ${quest.boss?"size-[96px]":"size-[76px]"} ${active?"border-[#b6ff22] bg-[#7439ee] text-white shadow-[0_0_0_9px_rgba(182,255,34,.08),0_9px_0_#4e279b] [animation:pulseRing_2s_infinite]":status==="completed"?"border-[#48485c] bg-[#2d2d3d] text-[#b6ff22] shadow-[0_7px_0_#15151e]":"border-[#373747] bg-[#242431] text-[#6f6f82]"}`}>{locked?<LockKeyhole size={25}/>:<Icon size={quest.boss?38:28}/>} {status==="completed"&&<span className="absolute -right-1 top-0 grid size-7 place-items-center rounded-full border-2 border-[#171720] bg-[#b6ff22] text-[#111]"><Check size={13} strokeWidth={4}/></span>}{quest.boss&&<span className="absolute -top-7 rounded-full bg-[#ff7658] px-3 py-1 text-[.46rem] font-black text-[#171720]">MONTHLY BOSS</span>}</div><div className={`panel min-w-[165px] p-3 md:min-w-[220px] ${active?"border-[#b6ff22]":""} ${quest.boss?"border-[#ff7658]/50":""} ${right?"text-left":"text-right"}`}><span className={`text-[.52rem] font-black tracking-[.14em] ${active?"text-[#b6ff22]":"text-[#858599]"}`}>{status.toUpperCase()}</span><b className="mt-1 block text-[.72rem] md:text-xs">{quest.name}</b><span className="mt-1 block text-[.55rem] font-bold text-[#858599]">{quest.distanceKm} KM • +{quest.rpReward} RP</span>{active&&<span className="mt-2 block text-[.5rem] font-black text-[#59e0dc]">TAP TO START →</span>}</div></button></div>}

export function QuestPath(){const {state,startQuest}=useGame(),router=useRouter(),progress=state.seasonState,quests=seasonQuestBlueprints.map(q=>personalizeSeasonQuest(q.id,state.runnerDNA)),current=quests.find(q=>q.id===progress.currentQuestId)??quests[0],overall=progress.completedQuestIds.length;if(progress.pathCompleted)return <section className="game-shape rounded-[2.3rem_2.3rem_1rem_2.3rem] bg-[#7439ee] p-7 text-center"><Trophy className="mx-auto text-[#b6ff22]" size={52}/><p className="mt-5 text-[.6rem] font-black tracking-[.18em] text-[#d8caff]">SEASON COMPLETE</p><h2 className="game-title mt-3 text-4xl">MONTHLY BOSS<br/><span className="text-[#b6ff22]">DEFEATED</span></h2><p className="mt-5 text-xs font-black">6 / 6 SEASON QUESTS • DAILY QUESTS CONTINUE</p><Link href="/leaderboard" className="lime-button mt-6">KEEP CLIMBING RANK</Link></section>;return <section><div className="mb-4 px-1"><div className="flex items-end justify-between"><div><p className="eyebrow">SEASON JOURNEY</p><h2 className="mt-1 text-xl font-black">{progress.season.monthLabel} QUEST</h2></div><Link href="/leaderboard" className="text-[.55rem] font-black text-[#b6ff22]">MONTHLY RANK →</Link></div><div className="mt-3 flex justify-between text-[.52rem] font-black text-[#9b9bad]"><span>SEASON PATH <b className="text-white">{overall} / 6</b></span><span><b className="text-white">{Math.round(overall/6*100)}%</b> COMPLETE</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#30303f]"><i className="block h-full rounded-full bg-gradient-to-r from-[#7439ee] to-[#b6ff22]" style={{width:`${overall/6*100}%`}}/></div></div><div className="relative overflow-hidden rounded-[2rem_2rem_1rem_2rem] border border-[#30303f] bg-[#11131f] px-2 py-6 md:px-12"><svg className="absolute inset-[3%_18%] h-[94%] w-[64%]" viewBox="0 0 420 740" preserveAspectRatio="none"><path d="M225 0C410 80 365 170 204 210S30 320 210 375s188 135 0 185S40 670 210 740" fill="none" stroke="#353548" strokeWidth="7" strokeLinecap="round" strokeDasharray="1 14"/></svg>{quests.map((quest,index)=>{const status=progress.completedQuestIds.includes(quest.id)?"completed":quest.id===progress.currentQuestId?"active":quest.order===current.order+1?"available":"locked";return <Node key={quest.id} quest={quest} index={index} status={status} onStart={()=>{startQuest(quest.id);router.push("/run")}}/>})}</div></section>}
