import { firstMainQuestId,mainQuests } from "@/data/journey";
import type { QuestAssignment,RunnerDNA } from "@/types/personalization";
import type { MainJourneyProgress,ObjectiveResult,ObjectiveRun,ProgressionEvaluation,RunObjective,SpecialEvent,WeeklyChallenge } from "@/types/progression";
const clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n));
export function initialJourneyProgress(now=new Date().toISOString()):MainJourneyProgress{return{completedQuestIds:[],currentQuestId:firstMainQuestId,bossesCompleted:0,startedAt:now,completedAt:null,mainJourneyCompleted:false,endGameUnlocked:false}}
export function personalizedMainObjectives(questId:string,dna:RunnerDNA):RunObjective[]{const quest=mainQuests.find(q=>q.id===questId);if(!quest)return[];return quest.objectives.map(o=>{if(o.kind!=="pace")return{...o,source:"main",sourceId:quest.id};const center=dna.avgPaceSecPerKm,margin=dna.experience==="advanced"?20:30;return{...o,source:"main",sourceId:quest.id,paceMinSecKm:center-margin,paceMaxSecKm:center+margin}})}
export function dailyObjectives(q:QuestAssignment):RunObjective[]{const out:RunObjective[]=[{id:`${q.id}-distance`,source:"daily",sourceId:q.id,kind:"distance",target:q.targetDistanceKm,xpReward:q.rewardXp,required:true}];if(q.checkpointCount)out.push({id:`${q.id}-checkpoints`,source:"daily",sourceId:q.id,kind:"checkpoint",target:q.checkpointCount,xpReward:0,required:true});if(q.partySize)out.push({id:`${q.id}-party`,source:"daily",sourceId:q.id,kind:"party",target:q.partySize[0],xpReward:0,required:true});if(q.targetPaceSecPerKm)out.push({id:`${q.id}-pace`,source:"daily",sourceId:q.id,kind:"pace",target:1,paceMinSecKm:q.targetPaceSecPerKm-25,paceMaxSecKm:q.targetPaceSecPerKm+25,xpReward:0,required:true});return out}
export function weeklyTargetKm(dna:RunnerDNA){return dna.experience==="beginner"?8:dna.experience==="advanced"?25:15}
export function createWeeklyChallenge(dna:RunnerDNA,now=new Date()):WeeklyChallenge{const day=(now.getUTCDay()+6)%7,start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-day)),key=start.toISOString().slice(0,10),target=weeklyTargetKm(dna);return{id:`weekly-${key}`,weekKey:key,title:`RUN ${target} KM THIS WEEK`,targetKm:target,progressKm:0,xpReward:Math.round(target*60),completed:false,claimed:false}}
export function eventObjectives(event:SpecialEvent):RunObjective[]{return event.active?[{id:`${event.id}-distance`,source:"event",sourceId:event.id,kind:"distance",target:event.distanceKm,xpReward:event.xpReward,required:true}]:[]}
function objectiveValue(o:RunObjective,run:ObjectiveRun){switch(o.kind){case"distance":return run.distanceKm;case"checkpoint":return run.checkpoints;case"pace":return run.paceSecKm!==null&&run.paceSecKm>=(o.paceMinSecKm??0)&&run.paceSecKm<=(o.paceMaxSecKm??Infinity)?1:0;case"social":return run.partySize>=2?1:0;case"party":return run.partySize;case"time":return run.elapsedSeconds;case"streak":return 1;case"exploration":return run.exploredNewRoute?1:0;case"boss":return 1;case"community":return 1}}
export function evaluateObjectives(objectives:RunObjective[],run:ObjectiveRun):ObjectiveResult[]{return objectives.map(o=>{const value=run.verified?objectiveValue(o,run):0,progress=clamp(value/Math.max(.001,o.target)),completed=run.verified&&progress>=1;return{objectiveId:o.id,source:o.source,sourceId:o.sourceId,completed,progress:Number(progress.toFixed(3)),xpAwarded:completed?o.xpReward:0}})}
export function evaluateProgression(objectives:RunObjective[],run:ObjectiveRun):ProgressionEvaluation{const evaluated=evaluateObjectives(objectives,run),groups=new Map<string,ObjectiveResult[]>();for(const r of evaluated){const key=`${r.source}:${r.sourceId}`;groups.set(key,[...(groups.get(key)??[]),r])}const complete=(source:string,id:string)=>groups.get(`${source}:${id}`)?.every(r=>r.completed)??false,results=evaluated.map(r=>complete(r.source,r.sourceId)?r:{...r,xpAwarded:0});const mainIds=[...new Set(results.filter(r=>r.source==="main").map(r=>r.sourceId))].filter(id=>complete("main",id)),seasonIds=[...new Set(results.filter(r=>r.source==="season").map(r=>r.sourceId))].filter(id=>complete("season",id)),eventIds=[...new Set(results.filter(r=>r.source==="event").map(r=>r.sourceId))].filter(id=>complete("event",id));return{results,completedMainQuestIds:mainIds,completedSeasonQuestIds:seasonIds,dailyCompleted:[...groups.keys()].some(k=>k.startsWith("daily:")&&groups.get(k)?.every(r=>r.completed)),weeklyCompleted:[...groups.keys()].some(k=>k.startsWith("weekly:")&&groups.get(k)?.every(r=>r.completed)),eventCompletedIds:eventIds,totalXp:results.reduce((n,r)=>n+r.xpAwarded,0)}}
export function advanceJourney(progress:MainJourneyProgress,completedIds:string[],level:number,totalDistanceKm:number,now=new Date().toISOString()):MainJourneyProgress{const merged=[...new Set([...progress.completedQuestIds,...completedIds])],last=mainQuests.at(-1),done=Boolean(last&&merged.includes(last.id)),current=mainQuests.find(q=>!merged.includes(q.id))?.id??last?.id??progress.currentQuestId,journeySeconds=done?Math.max(0,Math.floor((new Date(now).getTime()-new Date(progress.startedAt).getTime())/1000)):progress.totalJourneySeconds;return{...progress,completedQuestIds:merged,currentQuestId:current,bossesCompleted:mainQuests.filter(q=>q.boss&&merged.includes(q.id)).length,mainJourneyCompleted:done,endGameUnlocked:done,completedAt:done?(progress.completedAt??now):null,totalJourneySeconds:journeySeconds,finalLevel:done?level:progress.finalLevel,finalDistanceKm:done?totalDistanceKm:progress.finalDistanceKm,finalBadge:done?"CITY LEGEND":progress.finalBadge}}
