import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export const metadata:Metadata={title:"Terms of Service",description:"Terms for using the RUN QUEST running community service."};

export default function TermsPage(){return <LegalPage eyebrow="PLAY FAIR • RUN SAFE" title="TERMS OF SERVICE" updated="30 August 2026">
  <p>These Terms govern your use of RUN QUEST at runingquest.com. By creating an account or using the service, you agree to these Terms and our Privacy Policy. Questions may be sent to <a className="text-[#59e0dc] underline" href="mailto:running.quest.club@gmail.com">running.quest.club@gmail.com</a>.</p>
  <LegalSection title="1. Eligibility and accounts"><p>You must provide accurate account information, keep access to your account secure, and be legally able to accept these Terms. Users who are minors must have any permission required by local law. You are responsible for activity performed through your account.</p></LegalSection>
  <LegalSection title="2. Running and meetup safety"><p>Running, outdoor activity, GPS navigation, and meeting other people involve real risks. Check your health, weather, traffic, route, equipment, and surroundings; obey local laws; use public meeting places; and tell someone you trust about your plan. RUN QUEST does not provide emergency, medical, coaching, or navigation services. Call local emergency services when immediate help is needed.</p></LegalSection>
  <LegalSection title="3. Community conduct"><p>Do not harass, threaten, discriminate, impersonate, stalk, deceive, spam, exploit minors, publish another person&apos;s private location, organize illegal or unsafe activity, interfere with the service, or submit fake GPS or achievement data. Public meetup organizers and participants are independent users, not employees or screened representatives of RUN QUEST. Use your own judgment before meeting anyone.</p></LegalSection>
  <LegalSection title="4. Your content and public features"><p>You retain ownership of content you submit. You give us a limited, worldwide, non-exclusive license to host, process, display, and transmit that content only as needed to operate and improve RUN QUEST. Information you publish to maps, run spots, profiles, ranks, or matching features may be visible to other users. Only submit content you have the right to share.</p></LegalSection>
  <LegalSection title="5. Quests, GPS, ranks, and rewards"><p>GPS measurements can be inaccurate or unavailable. Distances, pace, matches, ranks, streaks, XP, and quest results are estimates and game features, not certified athletic records. Unless we expressly state otherwise, virtual XP, ranks, badges, and rewards have no monetary value and may be corrected, changed, or withdrawn when activity is invalid or abusive.</p></LegalSection>
  <LegalSection title="6. Suspension, cancellation, and service changes"><p>You may stop using the service at any time. We may remove content or restrict an account when reasonably necessary for safety, security, abuse prevention, legal compliance, or enforcement of these Terms. Features may change, experience interruption, or be discontinued. We will try to give reasonable notice of material changes when practical.</p></LegalSection>
  <LegalSection title="7. Disclaimers and responsibility"><p>The service is provided on an "as available" basis to the extent permitted by law. We do not guarantee uninterrupted operation, GPS accuracy, a successful match, the identity or conduct of another user, or the safety of any route or meetup. Nothing in these Terms excludes rights or responsibilities that cannot legally be excluded. You remain responsible for your choices, conduct, and safety while using the service.</p></LegalSection>
  <LegalSection title="8. Changes to these Terms"><p>We may update these Terms as RUN QUEST develops. The current version and updated date will remain available here. Continued use after an update takes effect means you accept the revised Terms, subject to rights provided by law.</p></LegalSection>
</LegalPage>}
