export type Language="en"|"th"|"lo";
type Localized={th:string;lo:string};

export const languageNames:Record<Language,string>={en:"EN",th:"ไทย",lo:"ລາວ"};

export const translations:Record<string,Localized>={
  "HOME":{th:"หน้าหลัก",lo:"ໜ້າຫຼັກ"},"EXPLORE":{th:"สำรวจ",lo:"ສຳຫຼວດ"},"RUN":{th:"วิ่ง",lo:"ແລ່ນ"},"SOCIAL":{th:"เข้าสังคม",lo:"ເຂົ້າສັງຄົມ"},"PROFILE":{th:"โปรไฟล์",lo:"ໂປຣໄຟລ໌"},
  "START":{th:"เริ่ม",lo:"ເລີ່ມ"},"RUNNERS":{th:"นักวิ่ง",lo:"ນັກແລ່ນ"},"ME":{th:"ฉัน",lo:"ຂ້ອຍ"},"START A RUN":{th:"เริ่มวิ่ง",lo:"ເລີ່ມແລ່ນ"},"CHECK GPS & START":{th:"ตรวจ GPS แล้วเริ่ม",lo:"ກວດ GPS ແລ້ວເລີ່ມ"},"OPEN START SCREEN →":{th:"เปิดหน้าเริ่มวิ่ง →",lo:"ເປີດໜ້າເລີ່ມແລ່ນ →"},
  "WELCOME BACK":{th:"ยินดีต้อนรับกลับ",lo:"ຍິນດີຕ້ອນຮັບກັບ"},"WHAT DO YOU WANT":{th:"วันนี้คุณอยาก",lo:"ມື້ນີ້ທ່ານຢາກ"},"TO DO":{th:"ทำอะไร",lo:"ເຮັດຫຍັງ"},"TODAY?":{th:"วันนี้?",lo:"ມື້ນີ້?"},"Check GPS and begin":{th:"ตรวจ GPS แล้วเริ่มวิ่ง",lo:"ກວດ GPS ແລ້ວເລີ່ມແລ່ນ"},"BROWSE QUESTS":{th:"เลือกภารกิจ",lo:"ເລືອກພາລະກິດ"},"Choose distance and route":{th:"เลือกระยะทางและเส้นทาง",lo:"ເລືອກໄລຍະທາງ ແລະເສັ້ນທາງ"},"FIND RUNNERS":{th:"ค้นหานักวิ่ง",lo:"ຄົ້ນຫານັກແລ່ນ"},"Match by pace and distance":{th:"จับคู่ตามเพซและระยะทาง",lo:"ຈັບຄູ່ຕາມເວລາຕໍ່ກິໂລແມັດ ແລະໄລຍະທາງ"},
  "RECOMMENDED FOR TODAY":{th:"แนะนำสำหรับวันนี้",lo:"ແນະນຳສຳລັບມື້ນີ້"},"REVIEW & START RUN":{th:"ตรวจสอบและเริ่มวิ่ง",lo:"ກວດເບິ່ງ ແລະເລີ່ມແລ່ນ"},"WHY THIS?":{th:"ทำไมเลือกอันนี้?",lo:"ເປັນຫຍັງເລືອກອັນນີ້?"},"CHANGE":{th:"เปลี่ยน",lo:"ປ່ຽນ"},"CHANGE QUEST":{th:"เปลี่ยนภารกิจ",lo:"ປ່ຽນພາລະກິດ"},
  "PRE-RUN CHECK":{th:"ตรวจความพร้อมก่อนวิ่ง",lo:"ກວດຄວາມພ້ອມກ່ອນແລ່ນ"},"READY TO":{th:"พร้อม",lo:"ພ້ອມ"},"RUN?":{th:"วิ่งไหม?",lo:"ແລ່ນບໍ?"},"READY TO RUN?":{th:"พร้อมวิ่งไหม?",lo:"ພ້ອມແລ່ນບໍ?"},"Your distance starts at 0.00 KM. It only increases from reliable GPS movement after you press Start.":{th:"ระยะทางเริ่มที่ 0.00 กม. และจะเพิ่มจากการเคลื่อนที่ผ่าน GPS ที่เชื่อถือได้หลังจากกดเริ่ม",lo:"ໄລຍະທາງເລີ່ມທີ່ 0.00 ກມ. ແລະຈະເພີ່ມຈາກການເຄື່ອນທີ່ຜ່ານ GPS ທີ່ເຊື່ອຖືໄດ້ຫຼັງກົດເລີ່ມ"},"SELECTED QUEST":{th:"ภารกิจที่เลือก",lo:"ພາລະກິດທີ່ເລືອກ"},"ALLOW LOCATION":{th:"อนุญาตตำแหน่ง",lo:"ອະນຸຍາດຕຳແໜ່ງ"},"Required to measure real distance":{th:"จำเป็นสำหรับวัดระยะทางจริง",lo:"ຈຳເປັນສຳລັບວັດໄລຍະທາງຈິງ"},"WAIT FOR GPS":{th:"รอ GPS เชื่อมต่อ",lo:"ລໍຖ້າ GPS ເຊື່ອມຕໍ່"},"Start moving after GPS connects":{th:"เริ่มเคลื่อนที่หลัง GPS เชื่อมต่อ",lo:"ເລີ່ມເຄື່ອນທີ່ຫຼັງ GPS ເຊື່ອມຕໍ່"},"RUN OUTDOORS":{th:"วิ่งกลางแจ้ง",lo:"ແລ່ນກາງແຈ້ງ"},"Open sky gives more accurate tracking":{th:"พื้นที่เปิดช่วยให้ติดตามแม่นยำขึ้น",lo:"ພື້ນທີ່ເປີດຊ່ວຍໃຫ້ຕິດຕາມແມ່ນຍຳຂຶ້ນ"},"START GPS TRACKING":{th:"เริ่มจับระยะด้วย GPS",lo:"ເລີ່ມຈັບໄລຍະດ້ວຍ GPS"},"CHOOSE ANOTHER QUEST":{th:"เลือกภารกิจอื่น",lo:"ເລືອກພາລະກິດອື່ນ"},"GPS POINTS":{th:"จุด GPS",lo:"ຈຸດ GPS"},"CONNECTING TO GPS…":{th:"กำลังเชื่อมต่อ GPS…",lo:"ກຳລັງເຊື່ອມຕໍ່ GPS…"},"LOCATION PERMISSION DENIED":{th:"ไม่ได้รับอนุญาตตำแหน่ง",lo:"ບໍ່ໄດ້ຮັບອະນຸຍາດຕຳແໜ່ງ"},"GPS UNAVAILABLE":{th:"ไม่พบ GPS",lo:"ບໍ່ພົບ GPS"},"RETRY":{th:"ลองอีกครั้ง",lo:"ລອງອີກຄັ້ງ"},"QUEST TARGET":{th:"เป้าหมายภารกิจ",lo:"ເປົ້າໝາຍພາລະກິດ"},"KM REMAINING":{th:"กม. ที่เหลือ",lo:"ກມ. ທີ່ເຫຼືອ"},
  "LEADERBOARD":{th:"อันดับ",lo:"ອັນດັບ"},"SETTINGS":{th:"ตั้งค่า",lo:"ຕັ້ງຄ່າ"},"QUEST MAP":{th:"แผนที่ภารกิจ",lo:"ແຜນທີ່ພາລະກິດ"},
  "DAILY QUEST":{th:"ภารกิจรายวัน",lo:"ພາລະກິດປະຈຳວັນ"},"RUN 2 KM":{th:"วิ่ง 2 กม.",lo:"ແລ່ນ 2 ກມ."},"WEEKLY QUEST":{th:"ภารกิจประจำสัปดาห์",lo:"ພາລະກິດປະຈຳອາທິດ"},
  "HOW IT WORKS":{th:"วิธีการเล่น",lo:"ວິທີຫຼິ້ນ"},"SAFETY":{th:"ความปลอดภัย",lo:"ຄວາມປອດໄພ"},"LOGIN":{th:"เข้าสู่ระบบ",lo:"ເຂົ້າລະບົບ"},"JOIN":{th:"เข้าร่วม",lo:"ເຂົ້າຮ່ວມ"},"JOIN RUN QUEST":{th:"เข้าร่วม RUN QUEST",lo:"ເຂົ້າຮ່ວມ RUN QUEST"},"CHOOSE YOUR":{th:"เลือกเส้นทาง",lo:"ເລືອກເສັ້ນທາງ"},"PATH.":{th:"ของคุณ",lo:"ຂອງທ່ານ"},"Create a new runner or continue with your existing account.":{th:"สร้างบัญชีนักวิ่งใหม่ หรือเข้าสู่บัญชีเดิมของคุณ",lo:"ສ້າງບັນຊີນັກແລ່ນໃໝ່ ຫຼືເຂົ້າສູ່ບັນຊີເກົ່າ"},"NEW RUNNER":{th:"นักวิ่งใหม่",lo:"ນັກແລ່ນໃໝ່"},"EXISTING RUNNER":{th:"สมาชิกเดิม",lo:"ສະມາຊິກເກົ່າ"},"Register a new runner profile":{th:"สมัครและสร้างโปรไฟล์นักวิ่งใหม่",lo:"ສະໝັກ ແລະສ້າງໂປຣໄຟລ໌ນັກແລ່ນໃໝ່"},"Continue your saved quest":{th:"เข้าสู่ระบบเพื่อเล่นภารกิจต่อ",lo:"ເຂົ້າລະບົບເພື່ອຫຼິ້ນພາລະກິດຕໍ່"},
  "REAL-WORLD ADVENTURE GAME":{th:"เกมผจญภัยในโลกจริง",lo:"ເກມຜະຈົນໄພໃນໂລກຈິງ"},"EVERY RUN":{th:"ทุกการวิ่ง",lo:"ທຸກການແລ່ນ"},"IS A":{th:"คือ",lo:"ແມ່ນ"},"QUEST.":{th:"ภารกิจ",lo:"ພາລະກິດ"},
  "Turn your city into an adventure. Find quests. Meet runners. Run together. Level up.":{th:"เปลี่ยนเมืองของคุณให้เป็นการผจญภัย ค้นหาภารกิจ พบเพื่อนนักวิ่ง วิ่งไปด้วยกัน และเลเวลอัป",lo:"ປ່ຽນເມືອງຂອງທ່ານໃຫ້ເປັນການຜະຈົນໄພ ຄົ້ນຫາພາລະກິດ ພົບໝູ່ນັກແລ່ນ ແລ່ນນຳກັນ ແລະເພີ່ມເລເວລ"},
  "START YOUR QUEST":{th:"เริ่มภารกิจ",lo:"ເລີ່ມພາລະກິດ"},"EXPLORE THE MAP":{th:"สำรวจแผนที่",lo:"ສຳຫຼວດແຜນທີ່"},"Privacy-first location and public meeting points":{th:"ปกป้องตำแหน่งส่วนตัวและนัดพบในพื้นที่สาธารณะ",lo:"ປົກປ້ອງຕຳແໜ່ງສ່ວນຕົວ ແລະນັດພົບໃນບ່ອນສາທາລະນະ"},
  "YOUR CITY IS THE GAME MAP.":{th:"เมืองของคุณคือแผนที่เกม",lo:"ເມືອງຂອງທ່ານຄືແຜນທີ່ເກມ"},"FIND YOUR QUEST":{th:"ค้นหาภารกิจ",lo:"ຄົ້ນຫາພາລະກິດ"},"MATCH YOUR RUNNER":{th:"จับคู่นักวิ่ง",lo:"ຈັບຄູ່ນັກແລ່ນ"},"RUN THE CITY":{th:"วิ่งทั่วเมือง",lo:"ແລ່ນທົ່ວເມືອງ"},"LEVEL UP":{th:"เลเวลอัป",lo:"ເພີ່ມເລເວລ"},
  "Choose a real-world mission built around your time and pace.":{th:"เลือกภารกิจในโลกจริงที่เหมาะกับเวลาและเพซของคุณ",lo:"ເລືອກພາລະກິດໃນໂລກຈິງທີ່ເໝາະກັບເວລາ ແລະຄວາມໄວຂອງທ່ານ"},"Build a party with runners who actually fit your style.":{th:"สร้างปาร์ตี้กับนักวิ่งที่เข้ากับสไตล์ของคุณ",lo:"ສ້າງປາຕີ້ກັບນັກແລ່ນທີ່ເຂົ້າກັບສະໄຕລ໌ຂອງທ່ານ"},"Use the real world as your controller. Hit every checkpoint.":{th:"ใช้โลกจริงเป็นคอนโทรลเลอร์และพิชิตทุกเช็กพอยต์",lo:"ໃຊ້ໂລກຈິງເປັນຕົວຄວບຄຸມ ແລະພິຊິດທຸກຈຸດກວດ"},"Earn XP, badges and unlock the next world.":{th:"รับ XP เหรียญตรา และปลดล็อกโลกถัดไป",lo:"ຮັບ XP, ຫຼຽນກາ ແລະປົດລັອກໂລກຕໍ່ໄປ"},
  "THE NEXT WORLD":{th:"โลกใบถัดไป",lo:"ໂລກຕໍ່ໄປ"},"WON'T UNLOCK ITSELF.":{th:"จะไม่ปลดล็อกด้วยตัวเอง",lo:"ຈະບໍ່ປົດລັອກດ້ວຍຕົນເອງ"},"PLAY RUN QUEST":{th:"เล่น RUN QUEST",lo:"ຫຼິ້ນ RUN QUEST"},
  "YOUR NEXT ADVENTURE":{th:"การผจญภัยครั้งต่อไป",lo:"ການຜະຈົນໄພຄັ້ງຕໍ່ໄປ"},"IS":{th:"กำลัง",lo:"ກຳລັງ"},"WAITING.":{th:"รอคุณอยู่",lo:"ລໍຖ້າທ່ານຢູ່"},
  "CITY EXPLORER":{th:"นักสำรวจเมือง",lo:"ນັກສຳຫຼວດເມືອງ"},"VIEW WORLD →":{th:"ดูโลก →",lo:"ເບິ່ງໂລກ →"},"NEXT QUEST":{th:"ภารกิจถัดไป",lo:"ພາລະກິດຕໍ່ໄປ"},"ACTIVE":{th:"กำลังเล่น",lo:"ກຳລັງຫຼິ້ນ"},"COMPLETED":{th:"สำเร็จแล้ว",lo:"ສຳເລັດແລ້ວ"},"AVAILABLE":{th:"พร้อมเล่น",lo:"ພ້ອມຫຼິ້ນ"},"LOCKED":{th:"ล็อก",lo:"ລັອກ"},
  "MORNING BOOST":{th:"พลังยามเช้า",lo:"ພະລັງຕອນເຊົ້າ"},"Run":{th:"วิ่ง",lo:"ແລ່ນ"},"before time runs out.":{th:"ก่อนหมดเวลา",lo:"ກ່ອນໝົດເວລາ"},"READY NEAR YOU":{th:"พร้อมวิ่งใกล้คุณ",lo:"ພ້ອມແລ່ນໃກ້ທ່ານ"},"SEE ALL":{th:"ดูทั้งหมด",lo:"ເບິ່ງທັງໝົດ"},"4 runners are ready":{th:"นักวิ่ง 4 คนพร้อมแล้ว",lo:"ນັກແລ່ນ 4 ຄົນພ້ອມແລ້ວ"},"FIND YOUR PARTY":{th:"ค้นหาปาร์ตี้",lo:"ຄົ້ນຫາປາຕີ້"},"WEEKLY WARRIOR":{th:"นักรบประจำสัปดาห์",lo:"ນັກຮົບປະຈຳອາທິດ"},"Run 20 KM this week":{th:"วิ่ง 20 กม. ในสัปดาห์นี้",lo:"ແລ່ນ 20 ກມ. ໃນອາທິດນີ້"},
  "PERSONAL QUEST MASTER":{th:"ผู้สร้างภารกิจเฉพาะคุณ",lo:"ຜູ້ສ້າງພາລະກິດສະເພາະທ່ານ"},"Choose what fits today.":{th:"เลือกสิ่งที่เหมาะกับวันนี้",lo:"ເລືອກສິ່ງທີ່ເໝາະກັບມື້ນີ້"},"GENERATE PERSONAL QUEST":{th:"สร้างภารกิจเฉพาะคุณ",lo:"ສ້າງພາລະກິດສະເພາະທ່ານ"},
  "PICK YOUR NEXT":{th:"เลือกการผจญภัย",lo:"ເລືອກການຜະຈົນໄພ"},"ADVENTURE.":{th:"ครั้งต่อไป",lo:"ຄັ້ງຕໍ່ໄປ"},"LIVE QUEST MAP":{th:"แผนที่ภารกิจสด",lo:"ແຜນທີ່ພາລະກິດສົດ"},"USE MY LOCATION":{th:"ใช้ตำแหน่งของฉัน",lo:"ໃຊ້ຕຳແໜ່ງຂອງຂ້ອຍ"},"LOCATING...":{th:"กำลังค้นหาตำแหน่ง...",lo:"ກຳລັງຊອກຫາຕຳແໜ່ງ..."},"LOCATION BLOCKED":{th:"ตำแหน่งถูกปิด",lo:"ຕຳແໜ່ງຖືກປິດ"},"QUESTS NEAR YOU":{th:"ภารกิจใกล้คุณ",lo:"ພາລະກິດໃກ້ທ່ານ"},"PREVIEW":{th:"ดูตัวอย่าง",lo:"ເບິ່ງຕົວຢ່າງ"},"PLAY":{th:"เล่น",lo:"ຫຼິ້ນ"},
  "QUEST DETAILS":{th:"รายละเอียดภารกิจ",lo:"ລາຍລະອຽດພາລະກິດ"},"← BACK TO MAP":{th:"← กลับไปแผนที่",lo:"← ກັບໄປແຜນທີ່"},"DISTANCE":{th:"ระยะทาง",lo:"ໄລຍະທາງ"},"EST. TIME":{th:"เวลาประมาณ",lo:"ເວລາໂດຍປະມານ"},"CHECKPOINTS":{th:"เช็กพอยต์",lo:"ຈຸດກວດ"},"DIFFICULTY":{th:"ความยาก",lo:"ຄວາມຍາກ"},"RECOMMENDED PACE":{th:"เพซแนะนำ",lo:"ເວລາຕໍ່ກິໂລແມັດທີ່ແນະນຳ"},"QUEST REWARD":{th:"รางวัลภารกิจ",lo:"ລາງວັນພາລະກິດ"},"BADGE REWARD":{th:"เหรียญรางวัล",lo:"ຫຼຽນລາງວັນ"},"START SOLO":{th:"เริ่มคนเดียว",lo:"ເລີ່ມຄົນດຽວ"},"START GPS RUN":{th:"เริ่มวิ่งด้วย GPS",lo:"ເລີ່ມແລ່ນດ້ວຍ GPS"},"FIND RUNNER":{th:"ค้นหานักวิ่ง",lo:"ຄົ້ນຫານັກແລ່ນ"},"FIND A PARTNER":{th:"หาเพื่อนวิ่ง",lo:"ຫາໝູ່ແລ່ນ"},
  "RUNNER MATCH":{th:"จับคู่นักวิ่ง",lo:"ຈັບຄູ່ນັກແລ່ນ"},"MULTIPLAYER MATCHMAKING":{th:"ระบบจับคู่ผู้เล่น",lo:"ລະບົບຈັບຄູ່ຜູ້ຫຼິ້ນ"},"FIND YOUR PERFECT":{th:"ค้นหาเพื่อนวิ่ง",lo:"ຄົ້ນຫາໝູ່ແລ່ນ"},"RUNNING PARTNER.":{th:"ที่เหมาะกับคุณ",lo:"ທີ່ເໝາະກັບທ່ານ"},"FILTERS":{th:"ตัวกรอง",lo:"ຕົວກອງ"},"PACE":{th:"เพซ",lo:"ເວລາ/ກມ."},"STREAK":{th:"สตรีก",lo:"ສະຕຣີກ"},"RUNNER RATING":{th:"คะแนนนักวิ่ง",lo:"ຄະແນນນັກແລ່ນ"},"VIEW PROFILE":{th:"ดูโปรไฟล์",lo:"ເບິ່ງໂປຣໄຟລ໌"},"INVITE":{th:"เชิญ",lo:"ເຊີນ"},
  "RUN SIGNAL":{th:"สัญญาณวิ่ง",lo:"ສັນຍານແລ່ນ"},"I'M READY TO":{th:"ฉันพร้อม",lo:"ຂ້ອຍພ້ອມ"},"Tell nearby runners what kind of adventure you want.":{th:"บอกนักวิ่งใกล้คุณว่าต้องการการผจญภัยแบบไหน",lo:"ບອກນັກແລ່ນໃກ້ທ່ານວ່າຕ້ອງການການຜະຈົນໄພແບບໃດ"},"WHEN":{th:"เมื่อไหร่",lo:"ເມື່ອໃດ"},"NOW":{th:"ตอนนี้",lo:"ຕອນນີ້"},"LATER":{th:"ภายหลัง",lo:"ພາຍຫຼັງ"},"PARTY TYPE":{th:"ประเภทปาร์ตี้",lo:"ປະເພດປາຕີ້"},"SEARCH RADIUS":{th:"รัศมีค้นหา",lo:"ລັດສະໝີຄົ້ນຫາ"},"AVAILABLE DURATION":{th:"เวลาที่ว่าง",lo:"ເວລາທີ່ວ່າງ"},"SEND RUN SIGNAL":{th:"ส่งสัญญาณวิ่ง",lo:"ສົ່ງສັນຍານແລ່ນ"},
  "RUNNING PARTY":{th:"ปาร์ตี้นักวิ่ง",lo:"ປາຕີ້ນັກແລ່ນ"},"YOUR RUNNING PARTY":{th:"ปาร์ตี้นักวิ่งของคุณ",lo:"ປາຕີ້ນັກແລ່ນຂອງທ່ານ"},"Get everyone ready. The city is waiting.":{th:"เตรียมทุกคนให้พร้อม เมืองกำลังรออยู่",lo:"ກຽມທຸກຄົນໃຫ້ພ້ອມ ເມືອງກຳລັງລໍຖ້າ"},"READY":{th:"พร้อม",lo:"ພ້ອມ"},"WAITING FOR PARTY...":{th:"กำลังรอปาร์ตี้...",lo:"ກຳລັງລໍຖ້າປາຕີ້..."},"START QUEST":{th:"เริ่มภารกิจ",lo:"ເລີ່ມພາລະກິດ"},"GET READY":{th:"เตรียมพร้อม",lo:"ກຽມພ້ອມ"},
  "LIVE QUEST":{th:"ภารกิจสด",lo:"ພາລະກິດສົດ"},"CURRENT DISTANCE":{th:"ระยะทางปัจจุบัน",lo:"ໄລຍະທາງປັດຈຸບັນ"},"TIME":{th:"เวลา",lo:"ເວລາ"},"NEXT CHECKPOINT":{th:"เช็กพอยต์ถัดไป",lo:"ຈຸດກວດຕໍ່ໄປ"},"PAUSE":{th:"พัก",lo:"ພັກ"},"RESUME":{th:"วิ่งต่อ",lo:"ແລ່ນຕໍ່"},"END RUN":{th:"จบการวิ่ง",lo:"ຈົບການແລ່ນ"},"END THIS RUN?":{th:"จบการวิ่งครั้งนี้?",lo:"ຈົບການແລ່ນຄັ້ງນີ້?"},"KEEP RUNNING":{th:"วิ่งต่อ",lo:"ແລ່ນຕໍ່"},"FINISH":{th:"เสร็จสิ้น",lo:"ສຳເລັດ"},
  "QUEST COMPLETE!":{th:"ภารกิจสำเร็จ!",lo:"ພາລະກິດສຳເລັດ!"},"RUN TRUST SCORE":{th:"คะแนนความน่าเชื่อถือ",lo:"ຄະແນນຄວາມໜ້າເຊື່ອຖື"},"XP EARNED":{th:"XP ที่ได้รับ",lo:"XP ທີ່ໄດ້ຮັບ"},"BADGE UNLOCKED":{th:"ปลดล็อกเหรียญ",lo:"ປົດລັອກຫຼຽນ"},"SHARE ACHIEVEMENT":{th:"แชร์ความสำเร็จ",lo:"ແບ່ງປັນຄວາມສຳເລັດ"},"CLAIM & CONTINUE":{th:"รับรางวัลและไปต่อ",lo:"ຮັບລາງວັນ ແລະໄປຕໍ່"},
  "PLAYER PROFILE":{th:"โปรไฟล์ผู้เล่น",lo:"ໂປຣໄຟລ໌ຜູ້ຫຼິ້ນ"},"TOTAL DISTANCE":{th:"ระยะทางรวม",lo:"ໄລຍະທາງລວມ"},"QUESTS":{th:"ภารกิจ",lo:"ພາລະກິດ"},"RUNNERS MET":{th:"นักวิ่งที่พบ",lo:"ນັກແລ່ນທີ່ພົບ"},"BADGES":{th:"เหรียญ",lo:"ຫຼຽນ"},"COLLECTION":{th:"คอลเลกชัน",lo:"ຄໍເລັກຊັນ"},"ACHIEVEMENTS":{th:"ความสำเร็จ",lo:"ຄວາມສຳເລັດ"},"SHARE PROFILE":{th:"แชร์โปรไฟล์",lo:"ແບ່ງປັນໂປຣໄຟລ໌"},
  "CITY LEADERBOARD":{th:"อันดับประจำเมือง",lo:"ອັນດັບປະຈຳເມືອງ"},"FRIENDS":{th:"เพื่อน",lo:"ໝູ່"},"WEEKLY":{th:"รายสัปดาห์",lo:"ປະຈຳອາທິດ"},"CITY":{th:"เมือง",lo:"ເມືອງ"},"QUEST":{th:"ภารกิจ",lo:"ພາລະກິດ"},
  "PRIVACY":{th:"ความเป็นส่วนตัว",lo:"ຄວາມເປັນສ່ວນຕົວ"},"APP":{th:"แอป",lo:"ແອັບ"},"Private profile":{th:"โปรไฟล์ส่วนตัว",lo:"ໂປຣໄຟລ໌ສ່ວນຕົວ"},"Location visibility":{th:"การแสดงตำแหน่ง",lo:"ການສະແດງຕຳແໜ່ງ"},"Match preferences":{th:"การตั้งค่าจับคู่",lo:"ການຕັ້ງຄ່າຈັບຄູ່"},"Quest notifications":{th:"การแจ้งเตือนภารกิจ",lo:"ການແຈ້ງເຕືອນພາລະກິດ"},"Account & security":{th:"บัญชีและความปลอดภัย",lo:"ບັນຊີ ແລະຄວາມປອດໄພ"},"DELETE RUN HISTORY":{th:"ลบประวัติการวิ่ง",lo:"ລຶບປະຫວັດການແລ່ນ"},"LOG OUT":{th:"ออกจากระบบ",lo:"ອອກຈາກລະບົບ"},
  "RUN WITH CONFIDENCE":{th:"วิ่งอย่างมั่นใจ",lo:"ແລ່ນຢ່າງໝັ້ນໃຈ"},"SAFETY IS PART":{th:"ความปลอดภัยคือส่วนหนึ่ง",lo:"ຄວາມປອດໄພແມ່ນສ່ວນໜຶ່ງ"},"OF THE QUEST.":{th:"ของภารกิจ",lo:"ຂອງພາລະກິດ"},"PUBLIC MEETING POINTS":{th:"จุดนัดพบสาธารณะ",lo:"ຈຸດນັດພົບສາທາລະນະ"},"EMERGENCY CONTACT":{th:"ผู้ติดต่อฉุกเฉิน",lo:"ຜູ້ຕິດຕໍ່ສຸກເສີນ"},"SHARE RUN":{th:"แชร์การวิ่ง",lo:"ແບ່ງປັນການແລ່ນ"},"BLOCK & REPORT":{th:"บล็อกและรายงาน",lo:"ບລັອກ ແລະລາຍງານ"},"REPORT A SAFETY ISSUE":{th:"รายงานปัญหาความปลอดภัย",lo:"ລາຍງານບັນຫາຄວາມປອດໄພ"},
  "WELCOME BACK, RUNNER":{th:"ยินดีต้อนรับกลับ นักวิ่ง",lo:"ຍິນດີຕ້ອນຮັບກັບ ນັກແລ່ນ"},"CONTINUE YOUR QUEST.":{th:"ทำภารกิจของคุณต่อ",lo:"ສືບຕໍ່ພາລະກິດຂອງທ່ານ"},"NEW PLAYER DETECTED":{th:"พบผู้เล่นใหม่",lo:"ພົບຜູ້ຫຼິ້ນໃໝ່"},"CREATE YOUR PLAYER.":{th:"สร้างตัวละครของคุณ",lo:"ສ້າງຕົວລະຄອນຂອງທ່ານ"},"EMAIL":{th:"อีเมล",lo:"ອີເມວ"},"PASSWORD":{th:"รหัสผ่าน",lo:"ລະຫັດຜ່ານ"},"CREATE ACCOUNT":{th:"สร้างบัญชี",lo:"ສ້າງບັນຊີ"},"ALREADY A PLAYER?":{th:"มีบัญชีอยู่แล้ว?",lo:"ມີບັນຊີແລ້ວ?"},"FORGOT PASSWORD?":{th:"ลืมรหัสผ่าน?",lo:"ລືມລະຫັດຜ່ານ?"},"CONTINUE WITH GOOGLE":{th:"ดำเนินการด้วย Google",lo:"ດຳເນີນການດ້ວຍ Google"},
  "CHARACTER CREATION":{th:"การสร้างตัวละคร",lo:"ການສ້າງຕົວລະຄອນ"},
  "YOUR RUNNER DNA":{th:"ดีเอ็นเอนักวิ่งของคุณ",lo:"DNA ນັກແລ່ນຂອງທ່ານ"},
  "Your real running behavior will refine this profile over time.":{th:"พฤติกรรมการวิ่งจริงของคุณจะช่วยปรับโปรไฟล์นี้ให้แม่นยำขึ้นเรื่อย ๆ",lo:"ພຶດຕິກຳການແລ່ນຈິງຂອງທ່ານຈະຊ່ວຍປັບໂປຣໄຟລ໌ນີ້ໃຫ້ແມ່ນຍຳຂຶ້ນເລື້ອຍໆ"},
  "DISPLAY NAME":{th:"ชื่อที่แสดง",lo:"ຊື່ສະແດງ"},"USERNAME":{th:"ชื่อผู้ใช้",lo:"ຊື່ຜູ້ໃຊ້"},"CHOOSE":{th:"เลือก",lo:"ເລືອກ"},"CHOOSE YOUR AVATAR":{th:"เลือกอวตารของคุณ",lo:"ເລືອກອາວະຕາຂອງທ່ານ"},"22 CHARACTERS":{th:"22 ตัวละคร",lo:"22 ຕົວລະຄອນ"},"MEN":{th:"ผู้ชาย",lo:"ຜູ້ຊາຍ"},"WOMEN":{th:"ผู้หญิง",lo:"ແມ່ຍິງ"},"ANIMALS & HEROES":{th:"สัตว์และฮีโร่",lo:"ສັດ ແລະ ຮີໂຣ"},
  "HOW OFTEN DO YOU RUN?":{th:"คุณวิ่งบ่อยแค่ไหน?",lo:"ທ່ານແລ່ນເລື້ອຍປານໃດ?"},"I'M JUST STARTING":{th:"เพิ่งเริ่มวิ่ง",lo:"ຫາກໍເລີ່ມແລ່ນ"},"1–2 TIMES / WEEK":{th:"1–2 ครั้ง / สัปดาห์",lo:"1–2 ຄັ້ງ / ອາທິດ"},"3–4 TIMES / WEEK":{th:"3–4 ครั้ง / สัปดาห์",lo:"3–4 ຄັ້ງ / ອາທິດ"},"5+ TIMES / WEEK":{th:"5 ครั้งขึ้นไป / สัปดาห์",lo:"5 ຄັ້ງຂຶ້ນໄປ / ອາທິດ"},
  "WHAT DISTANCE FEELS GOOD?":{th:"ระยะทางเท่าไรที่คุณวิ่งได้สบาย?",lo:"ໄລຍະທາງເທົ່າໃດທີ່ທ່ານແລ່ນໄດ້ສະບາຍ?"},"1–3 KM":{th:"1–3 กม.",lo:"1–3 ກມ."},"3–5 KM":{th:"3–5 กม.",lo:"3–5 ກມ."},"5–10 KM":{th:"5–10 กม.",lo:"5–10 ກມ."},"10+ KM":{th:"10 กม. ขึ้นไป",lo:"10 ກມ. ຂຶ້ນໄປ"},
  "WHAT'S YOUR USUAL PACE?":{th:"ปกติคุณใช้เวลากี่นาทีต่อกิโลเมตร?",lo:"ປົກກະຕິທ່ານໃຊ້ເວລາເທົ່າໃດຕໍ່ກິໂລແມັດ?"},"I DON'T KNOW YET":{th:"ยังไม่ทราบ",lo:"ຍັງບໍ່ຮູ້"},"7:00–8:00+ / KM":{th:"7:00–8:00+ นาที / กม.",lo:"7:00–8:00+ ນາທີ / ກມ."},"6:00–7:00 / KM":{th:"6:00–7:00 นาที / กม.",lo:"6:00–7:00 ນາທີ / ກມ."},"5:00–6:00 / KM":{th:"5:00–6:00 นาที / กม.",lo:"5:00–6:00 ນາທີ / ກມ."},"UNDER 5:00 / KM":{th:"ต่ำกว่า 5:00 นาที / กม.",lo:"ຕ່ຳກວ່າ 5:00 ນາທີ / ກມ."},
  "CHOOSE YOUR MAIN QUEST":{th:"เลือกภารกิจหลักของคุณ",lo:"ເລືອກພາລະກິດຫຼັກຂອງທ່ານ"},"GET HEALTHIER":{th:"สุขภาพแข็งแรงขึ้น",lo:"ເພື່ອສຸຂະພາບທີ່ດີຂຶ້ນ"},"BUILD CONSISTENCY":{th:"วิ่งให้สม่ำเสมอ",lo:"ແລ່ນໃຫ້ສະໝ່ຳສະເໝີ"},"RUN FASTER":{th:"วิ่งให้เร็วขึ้น",lo:"ແລ່ນໃຫ້ໄວຂຶ້ນ"},"EXPLORE THE CITY":{th:"สำรวจเมือง",lo:"ສຳຫຼວດເມືອງ"},"MEET RUNNERS":{th:"พบเพื่อนนักวิ่ง",lo:"ພົບປະນັກແລ່ນ"},"COMPETE":{th:"แข่งขัน",lo:"ແຂ່ງຂັນ"},"HAVE FUN":{th:"วิ่งให้สนุก",lo:"ແລ່ນໃຫ້ມ່ວນ"},
  "MORNING":{th:"ช่วงเช้า",lo:"ຕອນເຊົ້າ"},"AFTERNOON":{th:"ช่วงบ่าย",lo:"ຕອນບ່າຍ"},"EVENING":{th:"ช่วงเย็น",lo:"ຕອນແລງ"},"NIGHT":{th:"ช่วงกลางคืน",lo:"ຕອນກາງຄືນ"},
  "HOW SOCIAL SHOULD RUNS BE?":{th:"คุณอยากวิ่งร่วมกับผู้อื่นมากแค่ไหน?",lo:"ທ່ານຢາກແລ່ນຮ່ວມກັບຄົນອື່ນຫຼາຍປານໃດ?"},"MOSTLY SOLO":{th:"ส่วนใหญ่วิ่งคนเดียว",lo:"ສ່ວນໃຫຍ່ແລ່ນຄົນດຽວ"},"SOMETIMES WITH OTHERS":{th:"วิ่งกับคนอื่นเป็นบางครั้ง",lo:"ບາງຄັ້ງແລ່ນກັບຄົນອື່ນ"},"OFTEN WITH OTHERS":{th:"วิ่งกับคนอื่นบ่อย ๆ",lo:"ແລ່ນກັບຄົນອື່ນເລື້ອຍໆ"},"MEET NEW RUNNERS":{th:"พบเพื่อนนักวิ่งใหม่",lo:"ພົບນັກແລ່ນໃໝ່"},
  "CHOOSE YOUR PLAY STYLE":{th:"เลือกสไตล์การเล่นของคุณ",lo:"ເລືອກຮູບແບບການຫຼິ້ນຂອງທ່ານ"},"CASUAL":{th:"สบาย ๆ",lo:"ແບບສະບາຍໆ"},"FITNESS":{th:"เพื่อสุขภาพ",lo:"ເພື່ອສຸຂະພາບ"},"COMPETITIVE":{th:"สายแข่งขัน",lo:"ແບບແຂ່ງຂັນ"},"ADVENTURE":{th:"สายผจญภัย",lo:"ແບບຜະຈົນໄພ"},
  "Personalization guides your quests. You can always browse and choose something else.":{th:"การปรับให้เหมาะกับคุณช่วยแนะนำภารกิจ และคุณยังเลือกภารกิจอื่นได้เสมอ",lo:"ການປັບໃຫ້ເໝາະກັບທ່ານຊ່ວຍແນະນຳພາລະກິດ ແລະທ່ານຍັງສາມາດເລືອກພາລະກິດອື່ນໄດ້ສະເໝີ"},
  "PLAYER ARCHETYPE":{th:"รูปแบบผู้เล่น",lo:"ຮູບແບບຜູ້ຫຼິ້ນ"},"PACE STYLE":{th:"รูปแบบเพซ",lo:"ຮູບແບບເວລາຕໍ່ກິໂລແມັດ"},"PREFERRED DISTANCE":{th:"ระยะทางที่ต้องการ",lo:"ໄລຍະທາງທີ່ຕ້ອງການ"},"SPEED":{th:"ความเร็ว",lo:"ຄວາມໄວ"},"CONSISTENCY":{th:"ความสม่ำเสมอ",lo:"ຄວາມສະໝ່ຳສະເໝີ"},
  "PLAYER SETUP":{th:"ตั้งค่าผู้เล่น",lo:"ຕັ້ງຄ່າຜູ້ຫຼິ້ນ"},"CREATE YOUR PLAYER":{th:"สร้างตัวละคร",lo:"ສ້າງຕົວລະຄອນ"},"WHAT IS YOUR GENDER?":{th:"เพศของคุณคืออะไร?",lo:"ເພດຂອງທ່ານແມ່ນຫຍັງ?"},"WOMAN":{th:"หญิง",lo:"ແມ່ຍິງ"},"MAN":{th:"ชาย",lo:"ຜູ້ຊາຍ"},"NON-BINARY":{th:"นอนไบนารี",lo:"ບໍ່ຈຳກັດໃນສອງເພດ"},"PREFER NOT TO SAY":{th:"ไม่ประสงค์ระบุ",lo:"ບໍ່ຕ້ອງການລະບຸ"},"This helps personalize your profile and matching preferences.":{th:"ข้อมูลนี้ช่วยปรับโปรไฟล์และการตั้งค่าจับคู่ให้เหมาะกับคุณ",lo:"ຂໍ້ມູນນີ້ຊ່ວຍປັບໂປຣໄຟລ໌ ແລະການຕັ້ງຄ່າຈັບຄູ່ໃຫ້ເໝາະກັບທ່ານ"},"CHOOSE YOUR AGE RANGE":{th:"เลือกช่วงอายุ",lo:"ເລືອກຊ່ວງອາຍຸ"},"SET MATCH VISIBILITY":{th:"ตั้งค่าการจับคู่",lo:"ຕັ້ງຄ່າການຈັບຄູ່"},"SET YOUR RUNNING BASE":{th:"ตั้งค่าพื้นฐานการวิ่ง",lo:"ຕັ້ງຄ່າພື້ນຖານການແລ່ນ"},"CHOOSE YOUR LEVEL":{th:"เลือกระดับของคุณ",lo:"ເລືອກລະດັບຂອງທ່ານ"},"CHOOSE YOUR STYLE":{th:"เลือกสไตล์การวิ่ง",lo:"ເລືອກສະໄຕລ໌ການແລ່ນ"},"WHEN DO YOU RUN?":{th:"ปกติคุณวิ่งช่วงไหน?",lo:"ປົກກະຕິທ່ານແລ່ນໃນຊ່ວງໃດ?"},"MATCH SAFELY":{th:"จับคู่อย่างปลอดภัย",lo:"ຈັບຄູ່ຢ່າງປອດໄພ"},"BACK":{th:"ย้อนกลับ",lo:"ກັບຄືນ"},"CONTINUE":{th:"ดำเนินการต่อ",lo:"ດຳເນີນຕໍ່"},"ENTER WORLD":{th:"เข้าสู่โลก",lo:"ເຂົ້າສູ່ໂລກ"}
};

export function translate(source:string,language:Language){
  if(language==="en")return source;
  const exact=translations[source]?.[language];if(exact)return exact;
  let result=source;
  for(const [english,localized] of Object.entries(translations)){
    if(english.length>3&&result.includes(english))result=result.replaceAll(english,localized[language]);
  }
  return result;
}
