import { rankTiers,rpRewards,seasonQuestBlueprints } from "@/data/season";
import type { RunnerDNA } from "@/types/personalization";
import type { PersonalizedSeasonQuest,RankTier,RpAwardInput,RpAwardResult,SeasonDefinition,SeasonHistoryRecord,UserSeasonState } from "@/types/season";

const dayKey=(value:string|Date)=>new Date(value).toISOString().slice(0,10);
export function seasonForDate(now=new Date()):SeasonDefinition{const vientianeOffsetMs=7*60*60*1000,local=new Date(now.getTime()+vientianeOffsetMs),year=local.getUTCFullYear(),month=local.getUTCMonth(),starts=new Date(Date.UTC(year,month,1)-vientianeOffsetMs),ends=new Date(Date.UTC(year,month+1,1)-vientianeOffsetMs),monthLabel=local.toLocaleString("en-US",{month:"long",timeZone:"UTC"}).toUpperCase();return{id:`season-${year}-${String(month+1).padStart(2,"0")}`,number:month+1,name:`${monthLabel} SEASON`,monthLabel,startsAt:starts.toISOString(),endsAt:ends.toISOString(),badge:`${monthLabel} FINISHER`,active:now>=starts&&now<ends}}
export function daysRemaining(season:SeasonDefinition,now=new Date()){return Math.max(0,Math.ceil((new Date(season.endsAt).getTime()-now.getTime())/86_400_000))}
export function rankForRp(rp:number){return [...rankTiers].reverse().find(t=>rp>=t.minRp)??rankTiers[0]}
export function nextRank(rp:number){return rankTiers.find(t=>t.minRp>rp)??null}
export const rankLabel=(tier:RankTier)=>`${tier.name}${tier.division?` ${["","I","II","III"][tier.division]}`:""}`;
export function initialSeasonState(now=new Date(),startingRp=0):UserSeasonState{const season=seasonForDate(now),rank=rankForRp(startingRp);return{season,rp:startingRp,rankTierId:rank.id,highestRankTierId:rank.id,completedQuestIds:[],currentQuestId:seasonQuestBlueprints[0].id,bossCompleted:false,pathCompleted:false,activeDates:[],questCompletions:0,distanceKm:0,leaderboardPosition:0,startedAt:now.toISOString(),newcomerBonusClaimed:false,transactions:[]}}
export function personalizeSeasonQuest(questId:string,dna:RunnerDNA):PersonalizedSeasonQuest{const base=seasonQuestBlueprints.find(q=>q.id===questId)??seasonQuestBlueprints[0],preferred=dna.preferredDistanceKm,distance=base.boss?(dna.experience==="beginner"?Math.min(5,Math.max(3,preferred*1.4)):dna.experience==="advanced"?Math.min(10,Math.max(8,preferred)):Math.min(8,Math.max(5,preferred*1.35))):Math.max(1,Math.round(preferred*(.65+base.order*.08)*2)/2),checkpoints=base.kind==="checkpoint"?Math.max(2,Math.min(5,dna.difficultyTier)):base.boss?Math.max(2,Math.min(6,dna.difficultyTier+1)):0,partySize=base.kind==="social"?2:1,margin=dna.experience==="advanced"?20:35;return{...base,distanceKm:Number(distance.toFixed(1)),checkpoints,partySize,...(base.kind==="pace"?{paceMinSecKm:dna.avgPaceSecPerKm-margin,paceMaxSecKm:dna.avgPaceSecPerKm+margin}:{})}}
export function seasonQuestCompleted(quest:PersonalizedSeasonQuest,run:{distanceKm:number;paceSecKm:number|null;checkpoints:number;partySize:number;exploredNewRoute:boolean;verified:boolean}){if(!run.verified||run.distanceKm<quest.distanceKm)return false;if(quest.kind==="checkpoint"&&run.checkpoints<quest.checkpoints)return false;if(quest.kind==="social"&&run.partySize<2)return false;if(quest.kind==="exploration"&&!run.exploredNewRoute)return false;if(quest.kind==="pace"&&(run.paceSecKm===null||run.paceSecKm<(quest.paceMinSecKm??0)||run.paceSecKm>(quest.paceMaxSecKm??Infinity)))return false;return true}
export function awardRp(existing:UserSeasonState["transactions"],inputs:RpAwardInput[],dailyCap=rpRewards.dailyCap):RpAwardResult{const fresh=inputs.filter(input=>input.verified&&!existing.some(tx=>tx.seasonId===seasonForDate(new Date(input.createdAt)).id&&tx.source===input.source&&tx.sourceId===input.sourceId)),transactions=[] as UserSeasonState["transactions"];let awarded=0,capped=0;for(const input of fresh){const seasonId=seasonForDate(new Date(input.createdAt)).id,key=dayKey(input.createdAt),used=[...existing,...transactions].filter(tx=>dayKey(tx.createdAt)===key&&!["event","boss","newcomer"].includes(tx.source)).reduce((sum,tx)=>sum+tx.amount,0),room=input.capExempt?input.baseAmount:Math.max(0,dailyCap-used),amount=Math.min(input.baseAmount,room);capped+=input.baseAmount-amount;if(amount>0){transactions.push({id:`rp-${input.source}-${input.sourceId}-${key}`,seasonId,source:input.source,sourceId:input.sourceId,amount,createdAt:input.createdAt,verificationStatus:"verified"});awarded+=amount}}return{transactions,awarded,capped}}
export function advanceSeasonPath(state:UserSeasonState,completed:boolean,runDistance:number,completedAt:string,rpAwarded:number){const current=seasonQuestBlueprints.find(q=>q.id===state.currentQuestId)??seasonQuestBlueprints[0],completedIds=completed?[...new Set([...state.completedQuestIds,current.id])]:state.completedQuestIds,pathCompleted=completedIds.length===seasonQuestBlueprints.length,next=seasonQuestBlueprints.find(q=>!completedIds.includes(q.id))??seasonQuestBlueprints.at(-1)!,rp=state.rp+rpAwarded,rank=rankForRp(rp),highest=rankTiers.findIndex(t=>t.id===rank.id)>rankTiers.findIndex(t=>t.id===state.highestRankTierId)?rank.id:state.highestRankTierId;return{...state,rp,rankTierId:rank.id,highestRankTierId:highest,completedQuestIds:completedIds,currentQuestId:next.id,bossCompleted:completedIds.includes("season-boss"),pathCompleted,activeDates:[...new Set([...state.activeDates,dayKey(completedAt)])],questCompletions:state.questCompletions+(completed?1:0),distanceKm:Number((state.distanceKm+runDistance).toFixed(2))}}
export function finalizeSeason(state:UserSeasonState,endedAt=state.season.endsAt):SeasonHistoryRecord{return{seasonId:state.season.id,label:state.season.name,finalRankTierId:state.rankTierId,highestRankTierId:state.highestRankTierId,finalRp:state.rp,leaderboardPosition:state.leaderboardPosition,distanceKm:state.distanceKm,questCompletions:state.questCompletions,bossCompleted:state.bossCompleted,activeDays:state.activeDates.length,badge:state.pathCompleted?state.season.badge:undefined,endedAt}}
export function rolloverSeason(state:UserSeasonState,now=new Date()){const current=seasonForDate(now);if(current.id===state.season.id)return{state,history:null};return{state:initialSeasonState(now,0),history:finalizeSeason(state)}}
