import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/legal/legal-page";

export const metadata:Metadata={title:"Privacy Policy",description:"How RUN QUEST collects, uses, stores, and shares personal data."};

export default function PrivacyPage(){return <LegalPage eyebrow="YOUR DATA • YOUR CHOICE" title="PRIVACY POLICY" updated="30 August 2026">
  <p>This Privacy Policy explains how RUN QUEST ("we", "us", or "our") handles information when you use runingquest.com and the RUN QUEST running community service. Contact us at <a className="text-[#59e0dc] underline" href="mailto:running.quest.club@gmail.com">running.quest.club@gmail.com</a>.</p>
  <LegalSection title="1. Information we collect"><p>We collect account information such as your email address, display name, profile image or avatar, and the basic profile information you choose to provide. If you sign in with Google, we receive only the Google account data you authorize, normally your name, email address, profile image, and account identifier. We do not receive your Google password.</p><p className="mt-3">When you choose to record a run, we collect GPS coordinates, timestamps, distance, pace, route, and quest progress. We also process run spots, meetup participation, matching preferences, reports, blocks, streaks, XP, and other actions you intentionally submit. Basic device, browser, network, security, and diagnostic information may be processed when the service is used.</p></LegalSection>
  <LegalSection title="2. How we use information"><p>We use information to authenticate accounts; measure and verify runs; show progress, ranks, and achievements; operate public run spots and runner matching; protect users; prevent abuse or fake activity; troubleshoot the service; and communicate about accounts, safety, or material service changes.</p></LegalSection>
  <LegalSection title="3. Location privacy and public sharing"><p>GPS access begins only after you grant browser permission and start tracking. Public features may show a meetup point, approximate activity area, public route, display name, avatar, and run details that you choose to publish. RUN QUEST is designed to trim the beginning and end of eligible published routes to reduce disclosure of home or regular start locations. This protection cannot guarantee anonymity, so never publish a meetup at your home or another sensitive place. Your precise live position is not displayed to other runners as a live tracking feed.</p></LegalSection>
  <LegalSection title="4. Google user data"><p>Google Sign-In is used only to create and authenticate your RUN QUEST account and populate the basic profile fields described above. We do not sell Google user data, use it for advertising, or access Google Drive, Gmail, contacts, calendar, or other Google services. Our use and transfer of information received from Google APIs follows the Google API Services User Data Policy, including its Limited Use requirements.</p></LegalSection>
  <LegalSection title="5. Storage, service providers, and sharing"><p>Account and application data are hosted with Supabase; the website is hosted with Vercel; and Google provides optional sign-in. These providers may process technical information as needed to deliver and secure their services. We may also disclose information when required by law, to investigate abuse or a safety incident, or to protect the rights and safety of users. We do not sell personal information.</p></LegalSection>
  <LegalSection title="6. Retention and deletion"><p>We retain information while your account is active and as reasonably needed to operate, secure, and document the service. Public meetup pins may expire automatically based on their displayed duration. Safety and abuse records may be retained longer where necessary. You may request access, correction, export, or deletion by emailing us. Some limited records may be retained where required for security, fraud prevention, dispute resolution, or legal duties.</p></LegalSection>
  <LegalSection title="7. Your choices and security"><p>You can deny location permission, avoid publishing a run spot, leave a meetup, block or report a runner, and sign out at any time. You can also revoke RUN QUEST access from your Google Account settings. We use reasonable technical and organizational safeguards, but no online service can guarantee absolute security.</p></LegalSection>
  <LegalSection title="8. Children and changes"><p>RUN QUEST is not directed to children under 13, and local age rules may require a parent or guardian&apos;s permission. We may update this policy as the service changes. The updated date will appear at the top, and material changes may also be announced in the service.</p></LegalSection>
</LegalPage>}
