-- Deterministic Personalized Quest Engine storage.
create table public.runner_dna (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  experience_level text not null default 'beginner', avg_pace_sec_per_km int not null default 435,
  preferred_distance_km numeric not null default 3, main_goal text not null default 'health', preferred_time text not null default 'evening',
  preferred_quest_types text[] not null default '{}', social_score int not null default 50 check(social_score between 0 and 100),
  competition_score int not null default 30 check(competition_score between 0 and 100), exploration_score int not null default 50 check(exploration_score between 0 and 100),
  consistency_score int not null default 50 check(consistency_score between 0 and 100), weekly_target_runs int not null default 3,
  typical_run_duration_minutes int not null default 45, recent_activity_level int not null default 0, recovery_need int not null default 0,
  streak_behavior int not null default 0, quest_completion_rate numeric not null default .5, difficulty_tier int not null default 2 check(difficulty_tier between 1 and 10),
  archetype text not null default 'ALL-ROUNDER', confidence jsonb not null default '{}', updated_at timestamptz not null default now(), created_at timestamptz not null default now()
);
create table public.runner_behavior_metrics (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  runs_last_7_days int not null default 0, runs_last_30_days int not null default 0, distance_last_7_days numeric not null default 0,
  distance_last_30_days numeric not null default 0, avg_pace_last_30_days int, avg_distance_last_30_days numeric,
  quest_completion_rate numeric not null default 0, failed_quest_rate numeric not null default 0, abandoned_runs int not null default 0,
  social_run_ratio numeric not null default 0, hard_runs_last_7_days int not null default 0, days_since_last_run int,
  most_used_quest_type text, streak_days int not null default 0, updated_at timestamptz not null default now()
);
create table public.quest_templates (
  template_id text primary key, title_variants text[] not null, quest_type text not null, difficulty int not null check(difficulty between 1 and 10),
  min_level int not null default 1, distance_min_km numeric not null, distance_max_km numeric not null, xp_base int not null,
  is_social boolean not null default false, is_community boolean not null default false, checkpoint_min int not null default 0,
  checkpoint_max int not null default 0, duration_min_minutes int not null, duration_max_minutes int not null,
  goal_tags text[] not null default '{}', preferred_times text[] not null default '{}', cooldown_days int not null default 3,
  pace_pressure text not null default 'none', config jsonb not null default '{}', is_active boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.user_quest_assignments (
  id text primary key, user_id uuid not null references public.profiles(id) on delete cascade,
  quest_template_id text not null references public.quest_templates(template_id), generated_title text not null, quest_type text not null,
  difficulty int not null, difficulty_score numeric not null, target_distance_km numeric not null, target_pace_sec_per_km int,
  checkpoint_count int not null default 0, reward_xp int not null, party_size_min int, party_size_max int,
  assignment_type text not null, assigned_at timestamptz not null, expires_at timestamptz not null,
  accepted_at timestamptz, completed_at timestamptz, status text not null default 'assigned', personalization_score int not null,
  why_reasons text[] not null default '{}', generation_metadata jsonb not null default '{}', swap_reason text, created_at timestamptz not null default now()
);
create table public.runner_dna_history (
  id bigint generated by default as identity primary key, user_id uuid not null references public.profiles(id) on delete cascade,
  snapshot jsonb not null, change_reason text not null, created_at timestamptz not null default now()
);
create table public.daily_player_state (
  user_id uuid not null references public.profiles(id) on delete cascade, state_date date not null default current_date,
  player_state text not null, available_minutes int not null default 45, swaps_used int not null default 0,
  state_metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  primary key(user_id,state_date)
);

create index assignments_user_date_idx on public.user_quest_assignments(user_id,assigned_at desc);
create index assignments_cooldown_idx on public.user_quest_assignments(user_id,quest_template_id,assigned_at desc);
create index quest_templates_eligibility_idx on public.quest_templates(is_active,min_level,difficulty);
create index dna_history_user_time_idx on public.runner_dna_history(user_id,created_at desc);

insert into public.quest_templates(template_id,title_variants,quest_type,difficulty,min_level,distance_min_km,distance_max_km,xp_base,is_social,is_community,checkpoint_min,checkpoint_max,duration_min_minutes,duration_max_minutes,goal_tags,preferred_times,cooldown_days,pace_pressure) values
('easy_distance_run',array['EASY CITY STEP','FRESH START','CITY RESET'],'distance',2,1,1,5,200,false,false,0,2,15,60,array['health','consistency','fun'],array[]::text[],3,'none'),
('city_exploration',array['SUNSET DISCOVERY','CITY SECRETS','URBAN EXPLORER'],'exploration',4,2,2,10,350,false,false,2,6,25,100,array['exploration','fun','health'],array['afternoon','evening','night'],3,'light'),
('social_checkpoint_run',array['SOCIAL SUNSET','CHECKPOINT CREW','RUN TOGETHER'],'social',4,2,2,8,400,true,false,2,5,25,90,array['social','fun','exploration'],array[]::text[],2,'light'),
('pace_attack',array['PACE ATTACK','CITY PUSH','SPEED SPARK'],'speed',7,5,3,12,550,false,false,1,5,20,90,array['speed','competition'],array['morning','evening'],4,'target'),
('streak_builder',array['KEEP THE FLAME','CONSISTENCY LOOP','STREAK SAVER'],'consistency',3,1,1,6,250,false,false,0,3,15,60,array['consistency','health'],array[]::text[],2,'none'),
('recovery_walk_run',array['RECOVERY DAY','GENTLE RETURN','EASY MODE TODAY'],'recovery',1,1,1,4,180,false,false,0,2,15,45,array['health','consistency','fun'],array[]::text[],1,'none'),
('return_quest',array['WELCOME BACK','RETURN TO THE CITY','BACK ON THE PATH'],'returning',1,1,2,3,300,false,false,1,2,20,45,array['health','consistency','fun'],array[]::text[],14,'none'),
('community_weekend',array['VIENTIANE WEEKEND QUEST'],'community',4,1,2,10,450,true,true,1,4,20,120,array['social','exploration','fun','competition'],array[]::text[],7,'none')
on conflict(template_id) do update set title_variants=excluded.title_variants,updated_at=now();

alter table public.runner_dna enable row level security;
alter table public.runner_behavior_metrics enable row level security;
alter table public.quest_templates enable row level security;
alter table public.user_quest_assignments enable row level security;
alter table public.runner_dna_history enable row level security;
alter table public.daily_player_state enable row level security;
create policy "own runner dna" on public.runner_dna for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own behavior metrics" on public.runner_behavior_metrics for select using(user_id=auth.uid());
create policy "active quest templates" on public.quest_templates for select using(is_active);
create policy "own quest assignments" on public.user_quest_assignments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own dna history" on public.runner_dna_history for select using(user_id=auth.uid());
create policy "own daily state" on public.daily_player_state for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create trigger runner_dna_updated_at before update on public.runner_dna for each row execute function public.set_updated_at();
create trigger quest_templates_updated_at before update on public.quest_templates for each row execute function public.set_updated_at();
create trigger daily_player_state_updated_at before update on public.daily_player_state for each row execute function public.set_updated_at();

-- Keep summarized behavior current after a run changes. Raw GPS points never enter personalization queries.
create or replace function public.refresh_runner_behavior_metrics() returns trigger language plpgsql security definer set search_path=public as $$
declare uid uuid := new.user_id;
begin
  insert into public.runner_behavior_metrics(user_id,runs_last_7_days,runs_last_30_days,distance_last_7_days,distance_last_30_days,avg_pace_last_30_days,avg_distance_last_30_days,abandoned_runs,hard_runs_last_7_days,days_since_last_run,streak_days,quest_completion_rate,failed_quest_rate,updated_at)
  select uid,
    count(*) filter(where started_at>=now()-interval '7 days' and status='completed'),
    count(*) filter(where started_at>=now()-interval '30 days' and status='completed'),
    coalesce(sum(distance_km) filter(where started_at>=now()-interval '7 days' and status='completed'),0),
    coalesce(sum(distance_km) filter(where started_at>=now()-interval '30 days' and status='completed'),0),
    round(avg(average_pace) filter(where started_at>=now()-interval '30 days' and status='completed')*60),
    avg(distance_km) filter(where started_at>=now()-interval '30 days' and status='completed'),
    count(*) filter(where status in ('abandoned','failed')),
    count(*) filter(where started_at>=now()-interval '7 days' and distance_km>=8 and status='completed'),
    extract(day from now()-max(ended_at))::int,
    coalesce((select streak_days from public.profiles where id=uid),0),
    coalesce((select count(*) filter(where status='completed')::numeric/nullif(count(*),0) from public.user_quest_assignments where user_id=uid),.5),
    coalesce((select count(*) filter(where status in ('failed','expired'))::numeric/nullif(count(*),0) from public.user_quest_assignments where user_id=uid),0),now()
  from public.runs where user_id=uid
  on conflict(user_id) do update set runs_last_7_days=excluded.runs_last_7_days,runs_last_30_days=excluded.runs_last_30_days,distance_last_7_days=excluded.distance_last_7_days,distance_last_30_days=excluded.distance_last_30_days,avg_pace_last_30_days=excluded.avg_pace_last_30_days,avg_distance_last_30_days=excluded.avg_distance_last_30_days,abandoned_runs=excluded.abandoned_runs,hard_runs_last_7_days=excluded.hard_runs_last_7_days,days_since_last_run=excluded.days_since_last_run,streak_days=excluded.streak_days,quest_completion_rate=excluded.quest_completion_rate,failed_quest_rate=excluded.failed_quest_rate,updated_at=now();
  return new;
end $$;
create trigger refresh_behavior_after_run after insert or update of status,ended_at,distance_km,average_pace on public.runs for each row execute function public.refresh_runner_behavior_metrics();
