-- RUN QUEST initial schema. Apply with `supabase db push`.
create extension if not exists pgcrypto;

create or replace function public.set_updated_at() returns trigger language plpgsql security invoker set search_path = '' as $$ begin new.updated_at=now(); return new; end $$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null check (username ~ '^[a-z0-9_.]{3,24}$'), display_name text not null,
  avatar_url text, age_range text, gender text, level int not null default 1 check(level between 1 and 100),
  total_xp bigint not null default 0 check(total_xp>=0), title text not null default 'ROOKIE', city text,
  streak_days int not null default 0, runner_rating numeric(2,1) default 5.0,
  is_private boolean not null default false, location_visibility text not null default 'approximate' check(location_visibility in ('hidden','approximate')),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.runner_preferences (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  preferred_distance_min_km numeric not null default 3, preferred_distance_max_km numeric not null default 10,
  average_pace_min_km numeric, experience_level text, preferred_times text[] not null default '{}', running_styles text[] not null default '{}',
  match_genders text[] not null default '{}', max_radius_km numeric not null default 8 check(max_radius_km between 1 and 50),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.worlds (id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,number int unique not null,description text,color text,unlock_level int not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.quests (
 id uuid primary key default gen_random_uuid(),world_id uuid references public.worlds(id) on delete set null,slug text unique not null,name text not null,
 quest_type text not null,description text not null,distance_km numeric not null check(distance_km>0),duration_minutes int,
 pace_min numeric,pace_max numeric,difficulty int not null check(difficulty between 1 and 5),xp_reward int not null default 0,
 badge_reward text,sponsored_reward jsonb,requirements jsonb not null default '{}',is_active boolean not null default true,
 is_demo boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table public.quest_checkpoints (id uuid primary key default gen_random_uuid(),quest_id uuid not null references public.quests(id) on delete cascade,name text not null,checkpoint_order int not null,latitude double precision not null,longitude double precision not null,radius_meters int not null default 35,is_initially_revealed boolean not null default true,created_at timestamptz not null default now(),unique(quest_id,checkpoint_order));
create table public.quest_progress (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,quest_id uuid not null references public.quests(id) on delete cascade,status text not null default 'available',completion_percent int not null default 0,last_checkpoint_order int not null default 0,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(user_id,quest_id));
create table public.runs (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,quest_id uuid references public.quests(id) on delete set null,party_id uuid,status text not null default 'active',started_at timestamptz not null default now(),ended_at timestamptz,distance_km numeric,elapsed_seconds int,average_pace numeric,checkpoint_count int not null default 0,is_public boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.run_points (id bigint generated by default as identity primary key,run_id uuid not null references public.runs(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,captured_at timestamptz not null,latitude double precision not null,longitude double precision not null,accuracy_meters numeric,speed_mps numeric,created_at timestamptz not null default now());
create table public.run_verification (run_id uuid primary key references public.runs(id) on delete cascade,trust_score int not null check(trust_score between 0 and 100),status text not null check(status in ('verified','unverified','review')),flags jsonb not null default '[]',stats jsonb not null default '{}',verified_at timestamptz not null default now(),created_at timestamptz not null default now());
create table public.xp_transactions (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,run_id uuid references public.runs(id) on delete set null,quest_id uuid references public.quests(id) on delete set null,amount int not null,reason text not null,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create table public.achievements (id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text not null,icon text,rarity text not null default 'common',criteria jsonb not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_achievements (user_id uuid not null references public.profiles(id) on delete cascade,achievement_id uuid not null references public.achievements(id) on delete cascade,earned_at timestamptz not null default now(),metadata jsonb not null default '{}',primary key(user_id,achievement_id));
create table public.friendships (id uuid primary key default gen_random_uuid(),requester_id uuid not null references public.profiles(id) on delete cascade,addressee_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'pending',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(requester_id<>addressee_id),unique(requester_id,addressee_id));
create table public.run_signals (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'active',available_from timestamptz not null default now(),expires_at timestamptz not null,distance_km numeric,pace_min numeric,pace_max numeric,duration_minutes int,radius_km numeric not null default 5,party_type text not null default 'partner',approx_geohash text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.parties (id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete cascade,quest_id uuid references public.quests(id) on delete set null,status text not null default 'forming',max_members int not null default 4,meeting_point_name text,meeting_latitude double precision,meeting_longitude double precision,starts_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.runs add constraint runs_party_id_fkey foreign key(party_id) references public.parties(id) on delete set null;
create table public.party_members (party_id uuid not null references public.parties(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,status text not null default 'invited',joined_at timestamptz not null default now(),primary key(party_id,user_id));
create table public.leaderboards (id uuid primary key default gen_random_uuid(),period_type text not null,scope_type text not null,scope_value text,starts_at timestamptz not null,ends_at timestamptz not null,created_at timestamptz not null default now());
create table public.leaderboard_entries (leaderboard_id uuid not null references public.leaderboards(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,rank int,score numeric not null,verified_distance_km numeric not null default 0,updated_at timestamptz not null default now(),primary key(leaderboard_id,user_id));
create table public.rewards (id uuid primary key default gen_random_uuid(),name text not null,reward_type text not null,payload jsonb not null default '{}',inventory int,starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_rewards (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,reward_id uuid not null references public.rewards(id) on delete cascade,status text not null default 'earned',earned_at timestamptz not null default now(),claimed_at timestamptz,unique(user_id,reward_id));
create table public.reports (id uuid primary key default gen_random_uuid(),reporter_id uuid not null references public.profiles(id) on delete cascade,reported_user_id uuid references public.profiles(id) on delete set null,category text not null,details text,status text not null default 'open',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,kind text not null,title text not null,body text,data jsonb not null default '{}',read_at timestamptz,created_at timestamptz not null default now());

create index quest_checkpoints_quest_order_idx on public.quest_checkpoints(quest_id,checkpoint_order);
create index quest_progress_user_status_idx on public.quest_progress(user_id,status);
create index runs_user_started_idx on public.runs(user_id,started_at desc);
create index run_points_run_time_idx on public.run_points(run_id,captured_at);
create index xp_transactions_user_time_idx on public.xp_transactions(user_id,created_at desc);
create index run_signals_active_expiry_idx on public.run_signals(status,expires_at);
create index party_members_user_idx on public.party_members(user_id);
create index notifications_user_unread_idx on public.notifications(user_id,read_at) where read_at is null;

do $$ declare t text; begin foreach t in array array['profiles','runner_preferences','worlds','quests','quest_checkpoints','quest_progress','runs','run_points','run_verification','xp_transactions','achievements','user_achievements','friendships','run_signals','parties','party_members','leaderboards','leaderboard_entries','rewards','user_rewards','reports','notifications'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;

create policy "public game content" on public.worlds for select using(true);
create policy "public quests" on public.quests for select using(is_active);
create policy "public quest checkpoints" on public.quest_checkpoints for select using(exists(select 1 from public.quests q where q.id=quest_id and q.is_active));
create policy "public achievements" on public.achievements for select using(true);
create policy "public leaderboards" on public.leaderboards for select using(true);
create policy "public leaderboard entries" on public.leaderboard_entries for select using(true);
create policy "public rewards" on public.rewards for select using(now() between coalesce(starts_at,'-infinity') and coalesce(ends_at,'infinity'));
create policy "visible profiles" on public.profiles for select using(id=auth.uid() or not is_private);
create policy "own profile insert" on public.profiles for insert with check(id=auth.uid());
create policy "own profile update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "own preferences" on public.runner_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own quest progress" on public.quest_progress for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own runs" on public.runs for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own run points" on public.run_points for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own run verification" on public.run_verification for select using(exists(select 1 from public.runs r where r.id=run_id and r.user_id=auth.uid()));
create policy "own xp" on public.xp_transactions for select using(user_id=auth.uid());
create policy "visible earned achievements" on public.user_achievements for select using(user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=user_id and not p.is_private));
create policy "friendship participants" on public.friendships for all using(auth.uid() in (requester_id,addressee_id)) with check(auth.uid() in (requester_id,addressee_id));
create policy "own run signals" on public.run_signals for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "active approximate run signals" on public.run_signals for select using(status='active' and expires_at>now());
create policy "party owner" on public.parties for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "party member rows" on public.party_members for select using(user_id=auth.uid() or exists(select 1 from public.parties p where p.id=party_id and p.owner_id=auth.uid()));
create policy "join party" on public.party_members for insert with check(user_id=auth.uid() or exists(select 1 from public.parties p where p.id=party_id and p.owner_id=auth.uid()));
create policy "update own party status" on public.party_members for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own rewards" on public.user_rewards for select using(user_id=auth.uid());
create policy "own reward update" on public.user_rewards for update using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own reports" on public.reports for insert with check(reporter_id=auth.uid());
create policy "own report history" on public.reports for select using(reporter_id=auth.uid());
create policy "own notifications" on public.notifications for select using(user_id=auth.uid());
create policy "own notification update" on public.notifications for update using(user_id=auth.uid()) with check(user_id=auth.uid());

do $$ declare t text; begin foreach t in array array['profiles','runner_preferences','worlds','quests','quest_progress','runs','friendships','run_signals','parties','achievements','rewards','reports'] loop execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()',t||'_updated_at',t); end loop; end $$;
