"use client";

import { useEffect,useMemo,useRef,useState } from "react";
import type { FormEvent,PointerEvent as ReactPointerEvent } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { AlertTriangle,Crosshair,MapPin,Minus,Navigation,Plus,Trash2,Users,X } from "lucide-react";
import { quests } from "@/data/game-content";
import { useGeolocation } from "@/hooks/use-geolocation";
import { useRunSpots } from "@/hooks/use-run-spots";
import { useGame } from "@/components/state/game-provider";
import type { Coordinates,Quest,RunSpot } from "@/types/game";

const TILE_SIZE=256,INITIAL_CENTER={lat:17.968,lng:102.61};
const ZOOM_SENSITIVITY=3;
const color:Record<string,string>={easy:"#55df6a",medium:"#ff9a52",team:"#36bffa",boss:"#ff5e6c",mystery:"#9b79e8",night:"#7c42ff"};

function project({lat,lng}:Coordinates,zoom:number){const scale=TILE_SIZE*2**zoom,sin=Math.sin(Math.max(-85.0511,Math.min(85.0511,lat))*Math.PI/180);return{x:(lng+180)/360*scale,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale}}
function unproject(x:number,y:number,zoom:number):Coordinates{const scale=TILE_SIZE*2**zoom,n=Math.PI-2*Math.PI*y/scale;return{lng:x/scale*360-180,lat:180/Math.PI*Math.atan(Math.sinh(n))}}
function markerLabel(quest:Quest){return quest.type==="boss"?"🔥":quest.type==="team"?"👥":quest.type==="mystery"?"🎁":String(quest.distanceKm)}

export function GameMap({worldId}:{worldId:string}){
  const router=useRouter();
  const viewport=useRef<HTMLDivElement>(null),drag=useRef<{id:number;x:number;y:number;center:{x:number;y:number};lastX:number;lastY:number;lastTime:number;vx:number;vy:number}|null>(null),pointers=useRef(new Map<number,{x:number;y:number}>()),pinch=useRef<{distance:number;zoom:number;anchor:Coordinates}|null>(null),inertiaFrame=useRef<number|null>(null);
  const [size,setSize]=useState({width:0,height:0}),[center,setCenter]=useState<Coordinates>(INITIAL_CENTER),[zoom,setZoom]=useState(13),[selected,setSelected]=useState<Quest|null>(null),[selectedSpot,setSelectedSpot]=useState<RunSpot|null>(null),[selectedCluster,setSelectedCluster]=useState<RunSpot[]>([]),[selectedRoute,setSelectedRoute]=useState<Coordinates[]>([]),[routeLoading,setRouteLoading]=useState(false),[pinning,setPinning]=useState(false),[showForm,setShowForm]=useState(false),[dragging,setDragging]=useState(false),[tilesVisible,setTilesVisible]=useState(false),[tileErrors,setTileErrors]=useState(0);
  const [cancelTarget,setCancelTarget]=useState<RunSpot|null>(null),[cancelling,setCancelling]=useState(false);
  const {location,status,request}=useGeolocation(),{spots,viewerId,createSpot,joinSpot,leaveSpot,cancelSpot,loadRoute}=useRunSpots(),{state,notify}=useGame();

  useEffect(()=>{if(!viewport.current)return;const observer=new ResizeObserver(([entry])=>setSize({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(viewport.current);return()=>observer.disconnect()},[]);
  useEffect(()=>()=>{if(inertiaFrame.current!==null)cancelAnimationFrame(inertiaFrame.current)},[]);
  useEffect(()=>{if(location){setCenter(location);setZoom(15)}},[location]);
  const worldQuests=useMemo(()=>quests.filter(quest=>quest.worldId===worldId),[worldId]);
  useEffect(()=>{setSelected(null);setSelectedSpot(null);setSelectedCluster([]);setSelectedRoute([]);const points=worldQuests.map(quest=>quest.checkpoints[0]).filter(Boolean);if(points.length){setCenter({lat:points.reduce((sum,point)=>sum+point.lat,0)/points.length,lng:points.reduce((sum,point)=>sum+point.lng,0)/points.length});setZoom(14)}},[worldId,worldQuests]);
  const centerPixel=useMemo(()=>project(center,zoom),[center,zoom]);
  const tileZoom=Math.floor(zoom),tileScale=2**(zoom-tileZoom),tileCenterPixel=useMemo(()=>project(center,tileZoom),[center,tileZoom]);
  const tiles=useMemo(()=>{if(!size.width||!size.height)return[];const logicalWidth=size.width/tileScale,logicalHeight=size.height/tileScale,left=tileCenterPixel.x-logicalWidth/2,top=tileCenterPixel.y-logicalHeight/2,startX=Math.floor(left/TILE_SIZE)-1,endX=Math.floor((left+logicalWidth)/TILE_SIZE)+1,startY=Math.floor(top/TILE_SIZE)-1,endY=Math.floor((top+logicalHeight)/TILE_SIZE)+1,count=2**tileZoom,result:{key:string;src:string;left:number;top:number}[]=[];for(let rawY=startY;rawY<=endY;rawY++)for(let rawX=startX;rawX<=endX;rawX++){if(rawY<0||rawY>=count)continue;const x=((rawX%count)+count)%count;result.push({key:`${tileZoom}-${rawX}-${rawY}`,src:`/api/map-tiles/${tileZoom}/${x}/${rawY}`,left:size.width/2+(rawX*TILE_SIZE-tileCenterPixel.x)*tileScale,top:size.height/2+(rawY*TILE_SIZE-tileCenterPixel.y)*tileScale})}return result},[size,tileCenterPixel,tileScale,tileZoom]);

  function changeZoom(direction:number){setTilesVisible(false);setTileErrors(0);setZoom(value=>Math.max(3,Math.min(19,value+direction)))}
  function stopInertia(){if(inertiaFrame.current!==null){cancelAnimationFrame(inertiaFrame.current);inertiaFrame.current=null}}
  function zoomAt(nextZoom:number,clientX:number,clientY:number){const rect=viewport.current?.getBoundingClientRect();if(!rect)return;const next=Math.max(3,Math.min(19,nextZoom)),offsetX=clientX-rect.left-size.width/2,offsetY=clientY-rect.top-size.height/2,anchor=unproject(centerPixel.x+offsetX,centerPixel.y+offsetY,zoom),anchorNext=project(anchor,next);setCenter(unproject(anchorNext.x-offsetX,anchorNext.y-offsetY,next));setZoom(next)}
  function startInertia(vx:number,vy:number){if(Math.hypot(vx,vy)<.08)return;let last=performance.now(),pixel=project(center,zoom);const animate=(now:number)=>{const dt=Math.min(32,now-last);last=now;pixel={x:pixel.x+vx*dt,y:pixel.y+vy*dt};setCenter(unproject(pixel.x,pixel.y,zoom));const decay=Math.pow(.91,dt/16);vx*=decay;vy*=decay;if(Math.hypot(vx,vy)>.012)inertiaFrame.current=requestAnimationFrame(animate);else inertiaFrame.current=null};inertiaFrame.current=requestAnimationFrame(animate)}
  function pointerDown(event:ReactPointerEvent<HTMLDivElement>){if((event.target as HTMLElement).closest("button,a,input,textarea"))return;event.preventDefault();stopInertia();pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});event.currentTarget.setPointerCapture(event.pointerId);if(pointers.current.size===1){drag.current={id:event.pointerId,x:event.clientX,y:event.clientY,center:centerPixel,lastX:event.clientX,lastY:event.clientY,lastTime:performance.now(),vx:0,vy:0};setDragging(true)}else if(pointers.current.size===2){const [a,b]=[...pointers.current.values()],rect=viewport.current!.getBoundingClientRect(),midX=(a.x+b.x)/2,midY=(a.y+b.y)/2;pinch.current={distance:Math.hypot(b.x-a.x,b.y-a.y),zoom,anchor:unproject(centerPixel.x+(midX-rect.left-size.width/2),centerPixel.y+(midY-rect.top-size.height/2),zoom)};drag.current=null;setDragging(false)}}
  function pointerMove(event:ReactPointerEvent<HTMLDivElement>){if(!pointers.current.has(event.pointerId))return;event.preventDefault();pointers.current.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.current.size>=2&&pinch.current){const [a,b]=[...pointers.current.values()],rect=viewport.current!.getBoundingClientRect(),distance=Math.hypot(b.x-a.x,b.y-a.y),next=Math.max(3,Math.min(19,pinch.current.zoom+Math.log2(Math.max(20,distance)/Math.max(20,pinch.current.distance))*.72*ZOOM_SENSITIVITY)),midX=(a.x+b.x)/2-rect.left-size.width/2,midY=(a.y+b.y)/2-rect.top-size.height/2,anchor=project(pinch.current.anchor,next);setCenter(unproject(anchor.x-midX,anchor.y-midY,next));setZoom(next);return}const active=drag.current;if(active?.id===event.pointerId){const now=performance.now(),dt=Math.max(1,now-active.lastTime),instantVx=-(event.clientX-active.lastX)/dt,instantVy=-(event.clientY-active.lastY)/dt;active.vx=active.vx*.7+instantVx*.3;active.vy=active.vy*.7+instantVy*.3;active.lastX=event.clientX;active.lastY=event.clientY;active.lastTime=now;setCenter(unproject(active.center.x-(event.clientX-active.x),active.center.y-(event.clientY-active.y),zoom))}}
  function pointerUp(event:ReactPointerEvent<HTMLDivElement>){const released=drag.current?.id===event.pointerId?drag.current:null;pointers.current.delete(event.pointerId);if(released)drag.current=null;if(pointers.current.size<2)pinch.current=null;setDragging(false);if(event.currentTarget.hasPointerCapture?.(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(released&&pointers.current.size===0)startInertia(released.vx,released.vy)}
  useEffect(()=>{const node=viewport.current;if(!node)return;const handleWheel=(event:WheelEvent)=>{event.preventDefault();stopInertia();zoomAt(zoom-event.deltaY*.0022*ZOOM_SENSITIVITY,event.clientX,event.clientY)};node.addEventListener("wheel",handleWheel,{passive:false});return()=>node.removeEventListener("wheel",handleWheel)},[zoom,centerPixel,size.width,size.height]);
  function screenPoint(point:Coordinates){const pixel=project(point,zoom);return{x:pixel.x-centerPixel.x+size.width/2,y:pixel.y-centerPixel.y+size.height/2}}
  const routePath=selectedRoute.map(screenPoint);
  const spotClusters=clusterSpots(spots.map(spot=>({spot,point:screenPoint(spot)})).filter(item=>item.point.x>-70&&item.point.y>-70&&item.point.x<size.width+70&&item.point.y<size.height+70));
  const openSpot=async(spot:RunSpot)=>{setSelected(null);setSelectedCluster([]);setSelectedRoute([]);setSelectedSpot(spot);if(!spot.hasRoute)return;setRouteLoading(true);const route=await loadRoute(spot.id);setSelectedRoute(route);setRouteLoading(false)};
  const openCluster=(cluster:ReturnType<typeof clusterSpots>[number])=>{setSelected(null);setSelectedSpot(null);setSelectedRoute([]);const location={lat:cluster.items.reduce((sum,item)=>sum+item.spot.lat,0)/cluster.items.length,lng:cluster.items.reduce((sum,item)=>sum+item.spot.lng,0)/cluster.items.length};setCenter(location);if(zoom<17.5)setZoom(value=>Math.min(19,value+1.6));else setSelectedCluster(cluster.items.map(item=>item.spot))};

  return <div ref={viewport} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onDoubleClick={event=>zoomAt(zoom+1,event.clientX,event.clientY)} className={`relative z-0 isolate h-full min-h-[520px] touch-none overflow-hidden rounded-[1.5rem] border border-[#303348] bg-[#d9d6ce] ${dragging?"cursor-grabbing":"cursor-grab"}`}>
    <div className="absolute inset-0 bg-[radial-gradient(circle_at_center,#ece9e0,#cbc8c0)]"/>
    <div className="absolute inset-0 z-10 overflow-hidden" aria-label="Interactive street map of Vientiane">{tiles.map(tile=><img key={tile.key} src={tile.src} alt="" draggable={false} width={TILE_SIZE} height={TILE_SIZE} onLoad={()=>setTilesVisible(true)} onError={()=>setTileErrors(value=>value+1)} className="rq-map-tile absolute select-none will-change-transform" style={{left:tile.left,top:tile.top,transform:`scale(${tileScale})`,transformOrigin:"top left"}}/>)}</div>
    {routePath.length>1&&<svg className="pointer-events-none absolute inset-0 z-[16] h-full w-full"><polyline points={routePath.map(point=>`${point.x},${point.y}`).join(" ")} fill="none" stroke="#171720" strokeWidth="10" strokeLinecap="round" strokeLinejoin="round"/><polyline points={routePath.map(point=>`${point.x},${point.y}`).join(" ")} fill="none" stroke="#59e0dc" strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"/></svg>}
    <div className="absolute inset-0 z-20">
      {worldQuests.map(quest=>{const checkpoint=quest.checkpoints[0];if(!checkpoint)return null;const point=screenPoint(checkpoint);if(point.x<-60||point.y<-60||point.x>size.width+60||point.y>size.height+60)return null;return <button key={quest.id} onPointerDown={event=>event.stopPropagation()} onClick={()=>{setSelectedSpot(null);setSelectedRoute([]);setSelected(quest)}} aria-label={`Open ${quest.name}`} className="absolute grid size-11 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-[3px] border-[#101220] text-[.62rem] font-black text-[#111] shadow-[0_8px_22px_rgba(0,0,0,.35)] transition active:scale-90" style={{left:point.x,top:point.y,background:color[quest.type]||"#b6ff22"}}>{markerLabel(quest)}</button>})}
      {spotClusters.map(cluster=>{if(cluster.items.length>1){const runners=cluster.items.reduce((sum,item)=>sum+Math.max(1,item.spot.joinCount),0);return <button key={cluster.items.map(item=>item.spot.id).join("-")} onPointerDown={event=>event.stopPropagation()} onClick={()=>openCluster(cluster)} aria-label={`${cluster.items.length} runs nearby`} className="absolute grid size-16 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-[#171720] bg-[#59e0dc] text-[#171720] shadow-[0_9px_24px_rgba(0,0,0,.4)] active:scale-90" style={{left:cluster.x,top:cluster.y}}><b className="text-lg leading-none">{cluster.items.length}</b><small className="-mt-3 text-[7px] font-black">RUNS</small><span className="absolute -bottom-5 whitespace-nowrap rounded-full bg-[#171720] px-2 py-1 text-[7px] font-black text-white">{runners} RUNNERS</span></button>}const {spot,point}=cluster.items[0];return <button key={spot.id} onPointerDown={event=>event.stopPropagation()} onClick={()=>void openSpot(spot)} aria-label={`Run spot: ${spot.title}`} className="absolute -translate-x-1/2 -translate-y-full active:scale-90" style={{left:point.x,top:point.y}}><span className="relative grid size-12 place-items-center rounded-full border-4 border-[#171720] bg-[#7c42ff] text-xl shadow-[0_8px_20px_rgba(0,0,0,.4)]">{spot.ownerAvatar}{spot.hasRoute&&<span className="absolute -right-2 -top-2 grid size-5 place-items-center rounded-full border-2 border-[#171720] bg-[#59e0dc] text-[9px] text-[#171720]">↝</span>}<span className="absolute -bottom-2 left-1/2 size-4 -translate-x-1/2 rotate-45 border-b-4 border-r-4 border-[#171720] bg-[#7c42ff]"/></span><span className="relative mt-2 block rounded-full bg-[#171720] px-2 py-1 text-[8px] font-black text-white">{Math.max(1,spot.joinCount)} RUNNERS</span></button>})}
      {location&&(()=>{const point=screenPoint(location);return <span className="pointer-events-none absolute grid size-10 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-white bg-[#7439ee] text-white shadow-xl" style={{left:point.x,top:point.y}}>➤</span>})()}
    </div>
    <div className="glass absolute left-2 top-2 z-30 max-w-[calc(100%-4.5rem)] truncate rounded-xl px-2.5 py-2 text-[.5rem] font-black tracking-widest sm:left-3 sm:top-3 sm:px-3 sm:text-[.55rem]"><span className={`mr-2 inline-block size-1.5 rounded-full ${tilesVisible?"bg-[#55df6a]":"bg-[#ffd43b]"}`}/>{tilesVisible?"LIVE MAP":"LOADING MAP"}</div>
    <div className="absolute right-2 top-2 z-30 grid overflow-hidden rounded-xl border border-[#303348] bg-white text-[#171720] shadow-xl sm:right-3 sm:top-3"><button onPointerDown={event=>event.stopPropagation()} onClick={()=>changeZoom(1)} aria-label="Zoom in" className="grid size-9 place-items-center border-b border-[#d4d4d4] sm:size-11"><Plus size={20}/></button><button onPointerDown={event=>event.stopPropagation()} onClick={()=>changeZoom(-1)} aria-label="Zoom out" className="grid size-9 place-items-center sm:size-11"><Minus size={20}/></button></div>
    {!pinning&&<div className="pointer-events-none absolute left-1/2 top-14 z-30 max-w-[70%] -translate-x-1/2 truncate whitespace-nowrap rounded-full bg-[#171720]/85 px-3 py-1.5 text-[7px] font-black tracking-wider text-white sm:top-16 sm:text-[8px]">DRAG • PINCH TO ZOOM</div>}
    {pinning&&<><div className="pointer-events-none absolute left-1/2 top-1/2 z-30 -translate-x-1/2 -translate-y-full"><MapPin size={50} fill="#b6ff22" color="#171720"/></div><div className="absolute inset-x-3 bottom-20 z-30 rounded-2xl bg-[#171720] p-3 text-white shadow-2xl"><p className="text-[10px] font-black">MOVE THE MAP UNDER THE PIN</p><p className="mt-1 text-[9px] text-[#a8abba]">Choose a public meeting point, not your home.</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={()=>setPinning(false)} className="ghost-button !min-h-10">CANCEL</button><button onClick={()=>setShowForm(true)} className="lime-button !min-h-10">DROP PIN</button></div></div></>}
    {tileErrors>Math.max(3,tiles.length/2)&&<div role="alert" className="glass absolute right-3 top-28 z-30 max-w-44 rounded-xl p-3 text-[.52rem] font-black text-[#ff9b83]">MAP TILE ERROR<br/><span className="text-white">CHECK INTERNET CONNECTION</span></div>}
    {!pinning&&<div className="absolute inset-x-2 bottom-5 z-30 grid grid-cols-2 gap-2 sm:inset-x-auto sm:bottom-4 sm:left-4 sm:flex"><button onPointerDown={event=>event.stopPropagation()} onClick={request} className="ghost-button min-w-0 !min-h-11 !rounded-xl !px-2 !text-[.58rem] sm:!px-3"><Crosshair size={15}/><span className="truncate">{status==="loading"?"LOCATING...":status==="denied"?"LOCATION BLOCKED":"MY LOCATION"}</span></button><button onPointerDown={event=>event.stopPropagation()} onClick={()=>{setSelected(null);setSelectedSpot(null);setPinning(true)}} className="lime-button min-w-0 !min-h-11 !rounded-xl !px-2 !text-[.58rem] sm:!px-3"><MapPin size={15}/> PIN RUN</button></div>}
    <div className="absolute bottom-1 right-2 z-30 rounded bg-white/80 px-1.5 text-[9px] text-[#333]"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a></div>
    {selected&&<QuestPopup quest={selected} close={()=>setSelected(null)}/>} 
    {selectedSpot&&<RunSpotPopup spot={spots.find(item=>item.id===selectedSpot.id)||selectedSpot} viewerId={viewerId} routeLoading={routeLoading} routeVisible={routePath.length>1} close={()=>{setSelectedSpot(null);setSelectedRoute([])}} join={async()=>{try{const partyId=await joinSpot(selectedSpot.id);notify("Opening the shared run party");router.push(`/party/${partyId}`)}catch(error){notify(error instanceof Error?error.message:"Could not join this run")}}} leave={async()=>{try{await leaveSpot(selectedSpot.id);setSelectedSpot(current=>current?{...current,joined:false,joinCount:Math.max(1,current.joinCount-1)}:null);notify("You left this run party")}catch(error){notify(error instanceof Error?error.message:"Could not leave this run")}}} cancel={async()=>setCancelTarget(spots.find(item=>item.id===selectedSpot.id)||selectedSpot)}/>} 
    {selectedCluster.length>1&&<ClusterPopup spots={selectedCluster} close={()=>setSelectedCluster([])} choose={spot=>void openSpot(spot)}/>} 
    {showForm&&<PinForm center={center} close={()=>setShowForm(false)} submit={async values=>{try{const saved=await createSpot({ownerId:state.profile.username,ownerName:state.profile.displayName,ownerAvatar:state.profile.avatar,...values,position:center});setShowForm(false);setPinning(false);setSelectedSpot(saved);notify("Run spot published for 24 hours")}catch(error){notify(error instanceof Error?error.message:"Could not publish this run spot")}}}/>} 
    {cancelTarget&&<CancelRunDialog spot={cancelTarget} busy={cancelling} close={()=>{if(!cancelling)setCancelTarget(null)}} confirm={async()=>{setCancelling(true);try{await cancelSpot(cancelTarget.id);setCancelTarget(null);setSelectedSpot(null);notify("Public run cancelled")}catch(error){notify(error instanceof Error?error.message:"Could not cancel this run")}finally{setCancelling(false)}}}/>} 
  </div>;
}

type SpotPoint={spot:RunSpot;point:{x:number;y:number}};
function clusterSpots(items:SpotPoint[],distance=78){const clusters:{items:SpotPoint[];x:number;y:number}[]=[];for(const item of items){const nearby=clusters.find(cluster=>Math.hypot(cluster.x-item.point.x,cluster.y-item.point.y)<distance);if(!nearby){clusters.push({items:[item],x:item.point.x,y:item.point.y});continue}nearby.items.push(item);nearby.x=nearby.items.reduce((sum,current)=>sum+current.point.x,0)/nearby.items.length;nearby.y=nearby.items.reduce((sum,current)=>sum+current.point.y,0)/nearby.items.length}return clusters}

function ClusterPopup({spots,close,choose}:{spots:RunSpot[];close:()=>void;choose:(spot:RunSpot)=>void}){return <div className="panel pop absolute inset-x-3 bottom-3 z-40 max-h-[55%] overflow-hidden p-4 md:left-auto md:w-[370px]" onPointerDown={event=>event.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-[.5rem] font-black tracking-widest text-[#59e0dc]">SAME RUNNING AREA</p><h3 className="mt-1 text-sm font-black">{spots.length} RUNS TO CHOOSE</h3></div><button onClick={close} className="grid size-8 place-items-center rounded-full bg-[#30303e]"><X size={16}/></button></div><div className="mt-3 max-h-56 space-y-2 overflow-y-auto">{spots.map(spot=><button key={spot.id} onClick={()=>choose(spot)} className="flex w-full items-center gap-3 rounded-xl border border-[#343749] bg-[#1b1d2d] p-3 text-left"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-[#7c42ff] text-xl">{spot.ownerAvatar}</span><span className="min-w-0 flex-1"><b className="block truncate text-[.62rem]">{spot.title}</b><small className="mt-1 block text-[.5rem] text-[#8f93a5]">{spot.distanceKm} KM • {Math.max(1,spot.joinCount)} RUNNERS{spot.hasRoute?" • GPS ROUTE":""}</small></span><Navigation size={14} className="text-[#b7ff22]"/></button>)}</div></div>}

function QuestPopup({quest,close}:{quest:Quest;close:()=>void}){return <div className="panel pop absolute inset-x-3 bottom-3 z-40 p-4 md:left-auto md:w-[350px]" onPointerDown={event=>event.stopPropagation()}><button onClick={close} className="absolute right-3 top-3 text-[#898da0]"><X size={17}/></button><div className="flex gap-3"><span className="grid size-12 place-items-center rounded-2xl text-[#111]" style={{background:color[quest.type]||"#b6ff22"}}><MapPin size={21}/></span><div><p className="text-[.5rem] font-black tracking-widest text-[#8a8ea2]">OFFICIAL {quest.type.toUpperCase()} QUEST</p><h3 className="mt-1 text-sm font-black">{quest.name}</h3><p className="mt-1 text-[.58rem] text-[#8c90a2]">{quest.distanceKm} KM • {quest.checkpoints.length} CHECKPOINTS</p></div></div><p className="mt-3 rounded-lg bg-[#2a2d3e] px-3 py-2 text-[.52rem] font-black leading-4 text-[#aeb1c0]">TARGET MARKER ONLY • A ROUTE APPEARS AFTER A VERIFIED RUNNER SHARES REAL GPS DATA.</p><div className="mt-4 grid grid-cols-2 gap-2"><Link href={`/quest/${quest.id}`} className="ghost-button !min-h-11">PREVIEW</Link><Link href={`/quest/${quest.id}`} className="lime-button !min-h-11">PLAY <Navigation size={14}/></Link></div></div>}

function RunSpotPopup({spot,viewerId,routeLoading,routeVisible,close,join,leave,cancel}:{spot:RunSpot;viewerId:string;routeLoading:boolean;routeVisible:boolean;close:()=>void;join:()=>Promise<void>;leave:()=>Promise<void>;cancel:()=>Promise<void>}){const directions=`https://www.google.com/maps/dir/?api=1&destination=${spot.lat},${spot.lng}`,isOwner=spot.ownerId===viewerId,isFull=spot.joinCount>=spot.maxMembers;return <div className="panel pop absolute inset-x-3 bottom-3 z-40 p-4 md:left-auto md:w-[370px]" onPointerDown={event=>event.stopPropagation()}><button onClick={close} className="absolute right-3 top-3 text-[#898da0]"><X size={17}/></button><div className="flex gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#7c42ff] text-xl">{spot.ownerAvatar}</span><div className="pr-6"><p className="text-[.5rem] font-black tracking-widest text-[#b6ff22]">COMMUNITY RUN • {spot.ownerName}</p><h3 className="mt-1 text-sm font-black">{spot.title}</h3><p className="mt-1 text-[.58rem] text-[#8c90a2]">{spot.distanceKm} KM • MEETUP OPEN 24H</p></div></div>{spot.note&&<p className="mt-3 text-[.62rem] leading-5 text-[#c8cad4]">{spot.note}</p>}{spot.hasRoute&&<p className="mt-3 rounded-lg bg-[#223438] px-3 py-2 text-[.52rem] font-black text-[#59e0dc]">{routeLoading?"LOADING REAL GPS ROUTE…":routeVisible?"REAL GPS ROUTE SHOWN • PRIVATE ENDS HIDDEN":"ROUTE UNAVAILABLE"}</p>}<div className="mt-3 flex items-center gap-2 text-[.58rem] font-black"><Users size={14} color="#b6ff22"/>{spot.joinCount} / {spot.maxMembers} RUNNERS</div><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={isFull&&!spot.joined} onClick={()=>void join()} className="lime-button !min-h-11 disabled:opacity-40">{isOwner?"MANAGE PARTY":spot.joined?"OPEN PARTY":isFull?"PARTY FULL":"JOIN RUN"}</button><a href={directions} target="_blank" rel="noreferrer" className="ghost-button !min-h-11">DIRECTIONS <Navigation size={14}/></a></div>{isOwner?<button onClick={()=>void cancel()} className="mt-3 w-full text-[.52rem] font-black text-[#ff7f86]">CANCEL PUBLIC RUN</button>:spot.joined?<button onClick={()=>void leave()} className="mt-3 w-full text-[.52rem] font-black text-[#a7aabc]">LEAVE THIS PARTY</button>:null}</div>}

function CancelRunDialog({spot,busy,close,confirm}:{spot:RunSpot;busy:boolean;close:()=>void;confirm:()=>Promise<void>}){return <div role="dialog" aria-modal="true" aria-labelledby="cancel-run-title" className="absolute inset-0 z-[80] grid place-items-center bg-[#090a12]/85 p-4 backdrop-blur-sm" onPointerDown={event=>{event.stopPropagation();if(event.target===event.currentTarget)close()}}><div className="pop w-full max-w-sm overflow-hidden rounded-[1.75rem] border border-[#4a3b48] bg-[#20212f] shadow-[0_24px_80px_rgba(0,0,0,.65)]"><div className="h-1.5 bg-[#ff6573]"/><div className="p-5"><div className="flex items-start gap-3"><span className="grid size-12 shrink-0 place-items-center rounded-2xl bg-[#ff6573]/15 text-[#ff6573]"><AlertTriangle size={24}/></span><div className="min-w-0"><p className="text-[.5rem] font-black tracking-[.16em] text-[#ff7f89]">CANCEL PUBLIC RUN</p><h3 id="cancel-run-title" className="mt-1 text-lg font-black">REMOVE THIS MEETUP?</h3></div><button disabled={busy} onClick={close} aria-label="Close" className="ml-auto grid size-8 shrink-0 place-items-center rounded-full bg-[#303241] text-[#a5a8b7] disabled:opacity-40"><X size={16}/></button></div><div className="mt-4 rounded-2xl border border-[#343648] bg-[#191b29] p-4"><b className="block truncate text-xs">{spot.title}</b><p className="mt-2 text-[.58rem] leading-5 text-[#a7aab9]">The marker will disappear and the shared party will close for all <strong className="text-white">{spot.joinCount} runner{spot.joinCount===1?"":"s"}</strong>. This cannot be undone.</p></div><div className="mt-5 grid grid-cols-2 gap-2"><button disabled={busy} onClick={close} className="ghost-button !min-h-12 !rounded-xl disabled:opacity-40">KEEP RUN</button><button disabled={busy} onClick={()=>void confirm()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#ff6573] px-3 text-[.62rem] font-black text-[#171720] transition active:scale-95 disabled:opacity-50"><Trash2 size={15}/>{busy?"CANCELLING…":"CANCEL RUN"}</button></div></div></div></div>}

function PinForm({center,close,submit}:{center:Coordinates;close:()=>void;submit:(values:{title:string;note:string;distanceKm:number;pace:string;startsAt:string;maxMembers:number})=>Promise<void>}){const [saving,setSaving]=useState(false);async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);try{await submit({title:String(form.get("title")),note:String(form.get("note")),distanceKm:Number(form.get("distance")),pace:"NO PRESSURE",startsAt:new Date().toISOString(),maxMembers:Number(form.get("members"))})}finally{setSaving(false)}}return <div className="absolute inset-0 z-50 grid place-items-end bg-[#0c0d16]/65 p-2 md:place-items-center" onPointerDown={event=>event.stopPropagation()}><form onSubmit={save} className="panel max-h-[calc(100%-1rem)] w-full max-w-sm overflow-y-auto p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-[.5rem] font-black tracking-[.14em] text-[#b6ff22]">PUBLIC RUN PIN</p><h3 className="mt-1 text-base font-black">CREATE A RUN SPOT</h3></div><button type="button" onClick={close} aria-label="Close" className="grid size-8 shrink-0 place-items-center rounded-full bg-[#30303e]"><X size={17}/></button></div><p className="mt-3 rounded-xl bg-[#2a263e] px-3 py-2 text-[.52rem] leading-4 text-[#c8cad4]">Public for 24 hours • Creates one shared party • Don&apos;t pin your home</p><label className="mt-3 block text-[.5rem] font-black">RUN NAME<input required name="title" maxLength={80} defaultValue="COMMUNITY RUN" className="mt-1 h-11 w-full rounded-xl border border-[#3b3e50] bg-[#171927] px-3 text-[.68rem] font-bold text-white"/></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="block text-[.5rem] font-black">DISTANCE KM<input required name="distance" type="number" min="0.5" max="100" step="0.1" defaultValue="5" className="mt-1 h-11 w-full rounded-xl border border-[#3b3e50] bg-[#171927] px-3 text-[.68rem] font-bold text-white"/></label><label className="block text-[.5rem] font-black">MAX RUNNERS<select name="members" defaultValue="6" className="mt-1 h-11 w-full rounded-xl border border-[#3b3e50] bg-[#171927] px-3 text-[.68rem] font-bold text-white">{[2,3,4,5,6,8,10].map(value=><option key={value} value={value}>{value} PEOPLE</option>)}</select></label></div><label className="mt-3 block text-[.5rem] font-black">SHORT DETAILS <span className="font-normal text-[#85899b]">(OPTIONAL)</span><textarea name="note" maxLength={160} placeholder="Meeting point or useful note" className="mt-1 min-h-16 w-full resize-none rounded-xl border border-[#3b3e50] bg-[#171927] p-3 text-[.65rem] text-white"/></label><p className="mt-2 text-[7px] text-[#85899b]">PIN {center.lat.toFixed(5)}, {center.lng.toFixed(5)}</p><button disabled={saving} className="lime-button mt-3 w-full !min-h-11 !rounded-xl !text-[.65rem]">{saving?"PUBLISHING...":"PUBLISH RUN + PARTY"}</button></form></div>}
